// source: RehearsalResultMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage');
goog.provide('proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.displayName = 'proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.displayName = 'proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    correlationid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isfinal: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    currentslideindex: jspb.Message.getFieldWithDefault(msg, 4, 0),
    featuresMap: (f = msg.getFeaturesMap()) ? f.toObject(includeInstance, proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage;
  return proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsfinal(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCurrentslideindex(value);
      break;
    case 5:
      var value = msg.getFeaturesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.deserializeBinaryFromReader, "", new proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCorrelationid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsfinal();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getCurrentslideindex();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getFeaturesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.serializeBinaryToWriter);
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    featurevalue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    featuretemplate: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateinfoMap: (f = msg.getTemplateinfoMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo;
  return proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFeaturevalue(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFeaturetemplate(value);
      break;
    case 3:
      var value = msg.getTemplateinfoMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFeaturevalue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFeaturetemplate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateinfoMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string featureValue = 1;
 * @return {string}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.getFeaturevalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.setFeaturevalue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string featureTemplate = 2;
 * @return {string}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.getFeaturetemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.setFeaturetemplate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * map<string, string> templateInfo = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.getTemplateinfoMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo.prototype.clearTemplateinfoMap = function() {
  this.getTemplateinfoMap().clear();
  return this;};


/**
 * optional string correlationId = 1;
 * @return {string}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.getCorrelationid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.setCorrelationid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool isFinal = 3;
 * @return {boolean}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.getIsfinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.setIsfinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int32 currentSlideIndex = 4;
 * @return {number}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.getCurrentslideindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.setCurrentslideindex = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * map<string, FeatureInfo> features = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo>}
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.getFeaturesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.FeatureInfo));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage} returns this
 */
proto.Microsoft.PowerPoint.SpeechFrontDoor.ProtoBuf.RehearsalResultMessage.prototype.clearFeaturesMap = function() {
  this.getFeaturesMap().clear();
  return this;};


