/*
 ***************************************************************************************************** !*\
    !*** D:/a/_work/1/s/ooui/.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js ***!
    \**************************************************************************************************** no static exports found  ************************************ !*\
    !*** ./lib/DynamicScriptLoader.js ***!
    \*********************************** ./getOrderedScriptAndDependencies  ./loadScript  ./preloadScript  ********************************** !*\
    !*** ./lib/appResourceLoader.js ***!
    \********************************* ************************************************ !*\
    !*** ./lib/getOrderedScriptAndDependencies.js ***!
    \*********************************************** toposort  ********************** !*\
    !*** ./lib/index.js ***!
    \********************* ./DynamicScriptLoader  ./appResourceLoader  *************************** !*\
    !*** ./lib/loadScript.js ***!
    \************************** ****************************** !*\
    !*** ./lib/preloadScript.js ***!
    \******************************/
'use strict';var sA=window,jF=function(J){function V(w){for(var y=w[0],u=w[1],D,F,I=0,H=[];I<y.length;I++)F=y[I],Object.prototype.hasOwnProperty.call(e,F)&&e[F]&&H.push(e[F][0]),e[F]=0;for(D in u)Object.prototype.hasOwnProperty.call(u,D)&&(J[D]=u[D]);for(A&&A(w);H.length;)H.shift()()}function d(w){if(h[w])return h[w].exports;var y=h[w]={i:w,l:!1,exports:{}};J[w].call(y.exports,y,y.exports,d);y.l=!0;return y.exports}var h={},e={0:0};d.mil={1:"sha256-+aXYqQJOCQ4l7rICqzJfbtIr2Hqz5lsP0YbYcMKt7is=",2:"sha256-Ri1lPdn1Olh9YYXqNgogUFQDyRkR2VEF8lnzoZ+fYeA=",
3:"sha256-V35z0PrkqSmeli3yGRbZFi3uHYgojir5CRWoirc1EWg=",4:"sha256-Vhd5x0DahdgEkSaHBQ2il5/JLtdECh+vnzaNnNQCrms=",5:"sha256-2eWMjnIlHCBAKNrAByWMwDbueuEqPwjqs+4kV02gDKs=",6:"sha256-/hOYNLB97rg1hFgn2K/vKupaZLkIMIucZFajk0XBhFY=",7:"sha256-1DsyV41dz8ZPXGe+CWOqcxSP0RhOQs2IOHyN0B5Gq4k=",8:"sha256-A+MtspoGcQx4uVtwHMbQcV29RolHMLk5W50M5xpWqng=",9:"sha256-phJPA416vN88QrmU2sI0/YUIynavSzZ2s43gBXs5W+w=",10:"sha256-iFIdLO3mJ2aloH+JJcIMnxy/vHkyCroUbiwcBbfcNJQ=",11:"sha256-CXNYRYTpTrEKHeoU2O0l/5sw2w1GAe3ml3p3AyaWmSg=",
12:"sha256-A5WUPs29HnorL3H+gyjk7XDK3UrxVkiM6M3NwBPd4fA=",13:"sha256-Un4RklAlPm5MR94+Xm8xEH9sOsJmC6LQbDgUhrj1fg4=",14:"sha256-Zl4spdHLgxl8nE0jSSY1FGFERTVZCDrVQOQ9bgRtt7E=",15:"sha256-7XyBHdkJLuKB/tPZ4sdNns+pWm2vCX+BTEmBnWmrjHY=",16:"sha256-UNBUKFf/eDMjx3btj2/oVQFjHtfkFDeWqaNmSGNr0bo=",17:"sha256-Lg2xGC3ZEkxJwxrXI1NMAvXzrZr1v0AOg2jhHCPnreE=",18:"sha256-qVhZtv/klHMIUzqFdbqk4iM5vjNE+i3MmoK0cwyoZ/c="};d.e=function(w){var y=[],u=e[w];if(0!==u)if(u)y.push(u[2]);else{var D=new Promise(function(E,aa){u=e[w]=
[E,aa]});y.push(u[2]=D);var F=document.createElement("script");F.charset="utf-8";F.timeout=120;d.Egk&&F.setAttribute("nonce",d.Egk);F.src=d.p+"ppteditDS."+({1:"core",2:"chronos1",3:"ext",4:"presence1",5:"chronosslim",6:"extcommon",7:"comment",8:"chronos2",9:"appforoffice",10:"augloop",11:"presence",12:"smartlookup",13:"infrared",14:"ideas",15:"capture",16:"internal",17:"sortergrid",18:"animationpreview"}[w]||w)+".js";0!==F.src.indexOf(window.location.origin+"/")&&(F.crossOrigin="anonymous");var I=
Error();var H=function(E){F.onerror=F.onload=null;clearTimeout(L);var aa=e[w];if(0!==aa){if(aa){var Q=E&&("load"===E.type?"missing":E.type);E=E&&E.target&&E.target.src;I.message="Loading chunk "+w+" failed.\n("+Q+": "+E+")";I.name="ChunkLoadError";I.type=Q;I.request=E;aa[1](I)}e[w]=void 0}};var L=setTimeout(function(){H({type:"timeout",target:F})},12E4);F.onerror=F.onload=H;F.integrity=d.mil[w];F.crossOrigin="anonymous";document.head.appendChild(F)}return Promise.all(y)};d.m=J;d.c=h;d.d=function(w,
y,u){d.o(w,y)||Object.defineProperty(w,y,{enumerable:!0,get:u})};d.r=function(w){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(w,Symbol.toStringTag,{value:"Module"});Object.defineProperty(w,"__esModule",{value:!0})};d.t=function(w,y){y&1&&(w=d(w));if(y&8||y&4&&"object"===typeof w&&w&&w.caa)return w;var u=Object.create(null);d.r(u);Object.defineProperty(u,"default",{enumerable:!0,value:w});if(y&2&&"string"!=typeof w)for(var D in w)d.d(u,D,function(F){return w[F]}.bind(null,
D));return u};d.n=function(w){var y=w&&w.caa?function(){return w["default"]}:function(){return w};d.d(y,"a",y);return y};d.o=function(w,y){return Object.prototype.hasOwnProperty.call(w,y)};d.p="";var m=window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[],r=m.push.bind(m);m.push=V;m=m.slice();for(var v=0;v<m.length;v++)V(m[v]);var A=r;return d(d.s=18)}([function(J,V,d){d.d(V,"a",function(){return h});d.d(V,"b",function(){return e});const h=(m,r,v,A)=>{m.prototype.constructor=m;m.__typeName=
r;m.__class=!0;v&&(m.__baseType=v,m.__basePrototypePending=!1);0<A.length&&(m.__interfaces=A)},e=(m,r,v=!1)=>{r.__typeName=m;r.__string=m;r.__flags=v;r.__enum=!0;r.parse=A=>r[A];r.toString=A=>r[A];r.getName=()=>m}},function(J,V,d){J=d(0);class h extends Sys.EventArgs{constructor(m){super();this.Wi=m}}Object(J.a)(h,"UnobservedTaskExceptionEventArgs",Sys.EventArgs,[]);d.d(V,"a",function(){return e});class e{ETe(m){m.xoc()}static get events(){return e.Wya||(e.Wya=new Sys.EventHandlerList)}static get default(){return e._default}static get current(){return e.ry}static set current(m){e.ry=
m}static pjh(m,r){const {Task:v}=d(2);r=r||e.current;r===e._default?window.setTimeout(e.oYk(m,r),0):v.Create(m).Start$Scheduler(r)}static xEk(m,r){const v=e.events.getHandler("UnobservedException");v&&v(m,new h(r))}static oYk(m,r){return()=>{const v=e.current;e.current=r;m();e.current=v}}}e.Wya=null;Object(J.a)(e,"TaskScheduler",null,[])},function(J,V,d){d.r(V);J=d(0);var h=d(13),e=d(11),m=d(6),r=d(8);class v{constructor(D){this.Lm=D}xec(D){this.Lm.OC(D,null,0,null)}get isCompleted(){return this.Lm.isCompleted}ica(){if(this.Lm.hm)throw this.Lm.Wi;
if(this.Lm.Jn)throw r.a.uGc();}}Object(J.a)(v,"TaskAwaiter",null,[99]);class A{constructor(D,F,I){this.task=this.Axh=this.handler=null;this.token=D;this.options=F;this.vJb=I}}Object(J.a)(A,"Continuation",null,[]);var w=d(1);class y{constructor(){this.e1=[];this.SLa=!1;w.a.pjh(Object(h.a)(this,this.complete,"complete"),null)}complete(){this.SLa=!0;for(const D of this.e1)D()}get isCompleted(){return this.SLa}ica(){}xec(D){this.isCompleted?D():this.e1.push(D)}}Object(J.a)(y,"YieldAwaitable",null,[99]);
d.d(V,"Task",function(){return u});class u{constructor(){this.Yn=this.s0a=this.Ard=this.xnb=this.wLb=this.vjb=this.Hrc=null;this.iG=1}get id(){this._id||(this._id=++u.fTh);return this._id}get status(){return this.iG}get Wi(){return this.s0a}bhb(D){r.a.Stg(D)?this.w0():(this.s0a=D,this.KC(!1))}get Jn(){return 4===this.status}get isCompleted(){return 3<this.status}get hm(){return 5===this.status}g(){return new v(this)}w0(){this.R0(!1)||u.vyh()}R0(D){if(this.isCompleted||!D&&3===this.status)return!1;
this.iG=4;this.jjh();return!0}KC(D){this.btl(D)||u.vyh()}btl(D){if(this.isCompleted)return!1;this.iG=D?6:5;this.jjh();return!0}jjh(){const D=this.Hrc;this.Hrc=null;let F=!1;if(D)for(const I of D)F=this.Azh(I)||F;this.Wi&&!F&&w.a.xEk(this,this.Wi)}Azh(D){if(D.token&&D.token.IDa)return D.task&&D.task.R0(!1),!1;const F=this.Rni(D);D.task?u.$vi(D,F,D.vJb):u.Yvi(D,F,D.vJb,D.handler||(()=>{D.Axh(this)}));return F}Rni(D){return this.hm&&D.options&2||this.Jn&&D.options&1||6===this.status&&D.options&4?!1:
!0}rV(D,F,I,H){D=Object.assign(new A(F,I,H),{task:D});this.xHd(D)}OC(D,F,I,H){D=Object.assign(new A(F,I,H),{handler:D,token:F,vJb:H});this.xHd(D)}OCT(D,F,I,H){D=Object.assign(new A(F,I,H),{Axh:D,token:F,vJb:H});this.xHd(D)}xHd(D){D.vJb=D.vJb||w.a.current;if(D.token&&D.task){if(D.token.IDa&&this.ljg(D))return;D.token.R(()=>{this.ljg(D)})}this.isCompleted?this.Azh(D):this.Hrc=e.a(this.Hrc,D)}ljg(D){return D.task?D.task.R0(!1):!1}CW(D){return this.continueWith(D)}CWC(D,F){D=d(5).ContinuableTask.C(D,
this);this.rV(D,F,0,null);return D}CWo(D,F){return this.continueWith(D,F)}continueWith(D,F=0,I=null,H=null){D=d(5).ContinuableTask.C(D,this);this.rV(D,I,F,H);return D}CWT(D,F){D=d(5).ContinuableTask.C(D,this);this.rV(D,null,0,F);return D}CWO(D,F){D=d(5).ContinuableTask.CO(D,F,this);this.rV(D,null,0,null);return D}CWOC(D,F,I){D=d(5).ContinuableTask.CO(D,F,this);this.rV(D,I,0,null);return D}CWOo(D,F,I){D=d(5).ContinuableTask.CO(D,F,this);this.rV(D,null,I,null);return D}CWOT(D,F,I){D=d(5).ContinuableTask.CO(D,
F,this);this.rV(D,null,0,I);return D}CWCT(D,F,I,H){D=d(5).ContinuableTask.C(D,this);this.rV(D,F,I,H);return D}CWOCT(D,F,I,H,L){D=d(5).ContinuableTask.CO(D,F,this);this.rV(D,I,H,L);return D}CWR(D){return this.cwi(D)}cwi(D){D=d(7).ContinuableTask$1.C(D,this);this.rV(D,null,0,null);return D}CWRCC(D,F){D=d(7).ContinuableTask$1.C(D,this);this.rV(D,F,0,null);return D}CWRCo(D,F){D=d(7).ContinuableTask$1.C(D,this);this.rV(D,null,F,null);return D}CWRT(D,F){D=d(7).ContinuableTask$1.C(D,this);this.rV(D,null,
0,F);return D}CWRO(D,F){D=d(7).ContinuableTask$1.CO(D,F,this);this.rV(D,null,0,null);return D}CWRCT(D,F,I,H){D=d(7).ContinuableTask$1.C(D,this);this.rV(D,F,I,H);return D}CWROCT(D,F,I,H,L){D=d(7).ContinuableTask$1.CO(D,F,this);this.rV(D,I,H,L);return D}start(){this.Start$Scheduler(w.a.current)}Start$Scheduler(D){if(1!==this.status)throw Error.invalidOperation();this.xnb=D;this.iG=2;D.cEe(this)}xoc(){if(this.Ard&&this.Ard.IDa)this.isCompleted||this.w0();else if(!this.isCompleted){var D=w.a.current;
this.xnb=this.xnb||w.a.current;w.a.current=this.xnb||w.a.current;this.lgd();w.a.current=D}}lgd(){this.iG=3;try{if(!this.execute())throw Error.invalidOperation();this.KC(!0)}catch(D){r.a.Stg(D)?this.R0(!0):this.bhb(D)}}execute(){if(this.vjb)this.vjb();else if(this.wLb)this.wLb(this.Yn);else return!1;return!0}static get factory(){return u.wLa}static Create(D){return Object.assign(new u,{vjb:D})}static Create$object(D,F){return Object.assign(new u,{wLb:D,Yn:F})}static vyh(){throw Error.invalidOperation();
}static Yvi(D,F,I,H){F&&(D.options&8?H():w.a.pjh(H,I))}static $vi(D,F,I){const H=D.task;F?D.options&8?H.xoc():1===H.status&&(H.Ard=D.token,H.Start$Scheduler(I||w.a.current)):H.w0()}static delay(D){const F=new (d(16).CompletableTask);window.setTimeout(Object(h.a)(F,F.Dg,"setResult"),D);return F}static y(){return new y}static Gt(D){const F=new (d(12).CompletableTask$1);F.Dg(D);return F}static WAA(...D){return u.JCl.apply(null,D)}static JCl(...D){return u.WhenAllEnumerable(m.asEnumerable(D))}static WAE(D){return u.WhenAllEnumerable(D)}static WhenAllEnumerable(D){let F=
null,I=!1,H=0;const L=new (d(16).CompletableTask),E=aa=>{aa.hm&&(F=e.a(F,aa.Wi));aa.Jn&&(I=!0);H--;H||(F?L.SEsA(F):I?L.w0():L.Dg())};H++;for(const aa of D)H++,aa.isCompleted?E(aa):aa.OCT(E,null,0,null);H--;H||(F?L.SEsA(F):I?L.w0():L.Dg());return L}static When(D){let F=new (d(12).CompletableTask$1);const I=H=>{F&&(F.Dg(H),F=null)};for(const H of D){if(H.isCompleted)return u.Gt(H);H.OCT(I,null,0,null)}return F}static When$Result(D){let F=new (d(12).CompletableTask$1);for(const I of D){if(I.isCompleted)return u.Gt(I);
I.OCT(H=>{F&&(F.Dg(H),F=null)},null,0,null)}return F}}u.fTh=0;Object(J.a)(u,"Task",null,[])},,function(J,V,d){J=d(0);var h=d(2),e=d(8);class m{constructor(v){this.Lm=v}xec(v){this.Lm.OC(v,null,0,null)}get isCompleted(){return this.Lm.isCompleted}ica(){if(this.Lm.hm)throw this.Lm.Wi;if(this.Lm.Jn)throw e.a.uGc();return this.Lm.result}}Object(J.a)(m,"TaskAwaiter$1",null,[99]);d.d(V,"a",function(){return r});class r extends h.Task{constructor(){super();this.yud=this.xud=null}execute(){if(this.xud)this.ylc(this.xud());
else if(this.yud)this.ylc(this.yud(this.Yn));else return!1;return!0}get result(){if(6!==this.status)throw Error.invalidOperation();return this.Ex}ylc(v){this.Ex=v}G(){return new m(this)}static C(v){const A=new r;A.xud=v;return A}static CO(v,A){const w=new r;w.yud=v;w.Yn=A;return w}}Object(J.a)(r,"Task$1",h.Task,[])},function(J,V,d){d.r(V);d.d(V,"ContinuableTask",function(){return h});J=d(0);d=d(2);class h extends d.Task{constructor(){super();this._parent=this.TXe=this.Ipd=null}execute(){this.Ipd?
this.Ipd(this._parent):this.TXe(this._parent,this.Yn);return!0}static C(e,m){const r=new h;r.Ipd=e;r._parent=m;return r}static CO(e,m,r){const v=new h;v.TXe=e;v.Yn=m;v._parent=r;return v}}Object(J.a)(h,"ContinuableTask",d.Task,[])},function(J,V,d){d.r(V);J=d(0);var h=d(10);class e{constructor(fc){this.$$ge=this.getEnumerator;this.zH=fc}getEnumerator(){return new h.a(this.zH)}[Symbol.iterator](){return this.zH[Symbol.iterator]()}}Object(J.a)(e,"ArrayEnumerable$1",null,[141]);var m=d(17),r=d(21);class v{constructor(fc){this.gj=
null;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc}getEnumerator(){return this.Tu?new v(this.zt):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.get_current()}moveNext(){this.gj||(this.gj=this.zt.getEnumerator());return this.gj.moveNext()}reset(){this.gj=null}}Object(J.a)(v,"CastEnumerable",null,[141,142]);class A{constructor(fc,bc){this.iud=!1;this.r0a=null;this.Tu=
!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.qaa=fc;this.SRb=bc}getEnumerator(){return this.Tu?new A(this.qaa,this.SRb):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.r0a.$$cu()}moveNext(){this.r0a||(this.r0a=this.qaa.$$ge());if(this.r0a.$$mn())return!0;if(this.iud)return!1;this.iud=!0;this.r0a=this.SRb.$$ge();return this.r0a.$$mn()}reset(){this.iud=!1;this.r0a=null}}Object(J.a)(A,
"ConcatEnumerable",null,[141,142]);class w{constructor(){this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset}getEnumerator(){return this}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){throw Error.invalidOperation();}moveNext(){return!1}reset(){}}Object(J.a)(w,"EmptyEnumerator",null,[141,142]);class y{constructor(fc){this.zb=null;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.ztc=fc}get_current(){return this.ry}moveNext(){this.zb||
(this.zb=this.ztc());const fc=this.zb.next();this.ry=fc.value;return!fc.done}reset(){this.zb=null}}Object(J.a)(y,"IteratorEnumerator",null,[142]);class u{constructor(fc){this.$$ge=this.getEnumerator;this.ztc=fc}getEnumerator(){return new y(this.ztc)}[Symbol.iterator](){return this.ztc()}}Object(J.a)(u,"IteratorEnumerable",null,[141]);class D{constructor(fc,bc,cc,kb,ab){this.$$ge=this.getEnumerator;this.zt=fc;this.Z_e=bc;this._parent=kb;this.oLh=cc?(Pb,rc)=>cc.compare(Pb,rc):D.jsi.bind(D);this.RSh=
ab?-1:1}getEnumerator(){const fc=d(6).toArray(this.zt);fc.sort((bc,cc)=>this.QZf(bc,cc));return new h.a(fc)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}QZf(fc,bc){if(this._parent){const cc=this._parent.QZf(fc,bc);if(cc)return cc}return this.oLh(this.Z_e(fc),this.Z_e(bc))*this.RSh}static jsi(fc,bc){return fc<bc?-1:fc>bc?1:0}}Object(J.a)(D,"OrderByEnumerable",null,[1757,141]);class F{constructor(fc,bc){this.Ph=0;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=
this.moveNext;this.$$rst=this.reset;this._element=fc;this.Mk=bc}getEnumerator(){return this.Tu?(new F(this._element,this.Mk)).getEnumerator():(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this._element}moveNext(){if(this.Ph>=this.Mk)return!1;this.Ph++;return!0}reset(){this.Ph=0}}Object(J.a)(F,"RepeatEnumerator",null,[141,142]);class I{constructor(fc,bc,cc){this.Tu=!1;this.Ph=0;this.gj=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;
this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc;this.U0a=cc;this.lSb=bc}getEnumerator(){return this.Tu?new I(this.zt,this.lSb,this.U0a):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.ry}moveNext(){this.gj||(this.gj=this.zt.$$ge());return this.gj.$$mn()?(this.ry=this.jgd(this.gj.$$cu()),this.Ph++,!0):!1}next(){this.gj||(this.gj=this.zt.$$ge());return this.gj.$$mn()?(this.ry=this.jgd(this.gj.$$cu()),this.Ph++,{done:!1,value:this.ry}):
{done:!0,value:void 0}}reset(){this.gj=null;this.Ph=-1}jgd(fc){return this.U0a?this.U0a(fc,this.Ph):this.lSb(fc)}}Object(J.a)(I,"SelectEnumerator",null,[141,142]);class H{constructor(fc,bc,cc){this.Tu=!1;this.Ph=0;this.gj=this.g2a=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc;this.lSb=bc;this.U0a=cc}getEnumerator(){return this.Tu?new H(this.zt,this.lSb,this.U0a):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.g2a.$$cu()}moveNext(){if(this.g2a&&
this.g2a.$$mn())return!0;do{this.g2a=null;this.gj||(this.gj=this.zt.$$ge());if(!this.gj.$$mn())return!1;this.g2a=this.jgd(this.gj.$$cu()).$$ge();this.Ph++}while(!this.g2a.$$mn());return!0}reset(){this.g2a=this.gj=null;this.Ph=0}jgd(fc){return this.U0a?this.U0a(fc,this.Ph):this.lSb(fc)}}Object(J.a)(H,"SelectManyEnumerator",null,[141,142]);class L{constructor(fc,bc){this.gj=null;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=
fc;this.Mk=bc}getEnumerator(){return this.Tu?new L(this.zt,this.Mk):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.$$cu()}moveNext(){if(!this.gj){this.gj=this.zt.$$ge();for(let fc=0;fc<this.Mk;fc++)if(!this.gj.$$mn())return!1}return this.gj.$$mn()}reset(){this.gj=null}}Object(J.a)(L,"SkipEnumerator",null,[141,142]);class E{constructor(fc,bc,cc){this.Tu=!1;this.Ph=0;this.gj=null;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=
this.moveNext;this.$$rst=this.reset;this.zt=fc;this.kSb=bc;this.T0a=cc}getEnumerator(){return this.Tu?new E(this.zt,this.kSb,this.T0a):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.$$cu()}moveNext(){if(this.gj)return this.gj.$$mn();for(this.gj=this.zt.$$ge();this.gj.$$mn();){if(!this.aWd(this.gj.$$cu()))return!0;this.Ph++}return!1}reset(){this.gj=null;this.Ph=0}aWd(fc){return this.T0a?this.T0a(fc,this.Ph):this.kSb(fc)}}Object(J.a)(E,"SkipWhileEnumerator",
null,[141,142]);class aa{constructor(fc,bc){this.Ph=0;this.gj=null;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc;this.Mk=bc}getEnumerator(){return this.Tu?new aa(this.zt,this.Mk):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.$$cu()}moveNext(){this.gj||(this.gj=this.zt.$$ge());if(this.Ph>=this.Mk)return!1;this.Ph++;return this.gj.$$mn()}reset(){this.gj=null}}Object(J.a)(aa,
"TakeEnumerator",null,[141,142]);class Q{constructor(fc,bc,cc){this.Tu=!1;this.Ph=0;this.gj=null;this.$rd=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc;this.kSb=bc;this.T0a=cc}getEnumerator(){return this.Tu?new Q(this.zt,this.kSb,this.T0a):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.$$cu()}moveNext(){if(this.$rd)return!1;this.gj||(this.gj=this.zt.$$ge());if(!this.gj.$$mn()||
!this.aWd(this.gj.$$cu()))return this.$rd=!0,this.gj=null,!1;this.Ph++;return!0}reset(){this.gj=null;this.Ph=0}aWd(fc){return this.T0a?this.T0a(fc,this.Ph):this.kSb(fc)}}Object(J.a)(Q,"TakeWhileEnumerator",null,[141,142]);class O{constructor(fc,bc){this.gj=null;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.zt=fc;this.ynb=bc}getEnumerator(){return this.Tu?new O(this.zt,this.ynb):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.gj.$$cu()}moveNext(){this.gj||
(this.gj=this.zt.$$ge());for(;this.gj.$$mn();)if(this.ynb(this.gj.$$cu()))return!0;return!1}next(){this.gj||(this.gj=this.zt.$$ge());for(;this.gj.$$mn();)if(this.ynb(this.gj.$$cu()))return{done:!1,value:this.gj.$$cu()};return{done:!0,value:void 0}}reset(){this.gj=null}}Object(J.a)(O,"WhereEnumerator",null,[141,142]);class T{constructor(fc,bc,cc){this.oyc=this.LNb=null;this.Tu=!1;this.$$ge=this.getEnumerator;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=this.reset;this.qaa=fc;this.SRb=
bc;this.zuf=cc}getEnumerator(){return this.Tu?new T(this.qaa,this.SRb,this.zuf):(this.Tu=!0,this)}[Symbol.iterator](){return Object(r.a)(this.getEnumerator())}get_current(){return this.ry}moveNext(){this.LNb||(this.LNb=this.qaa.$$ge(),this.oyc=this.SRb.$$ge());return this.LNb.$$mn()&&this.oyc.$$mn()?(this.ry=this.zuf(this.LNb.$$cu(),this.oyc.$$cu()),!0):!1}reset(){this.oyc=this.LNb=null}}Object(J.a)(T,"ZipEnmerator",null,[141,142]);d.d(V,"asEnumerable",function(){return K});d.d(V,"fromIterator",function(){return X});
d.d(V,"select",function(){return P});d.d(V,"Si",function(){return ea});d.d(V,"SMi",function(){return ia});d.d(V,"selectMany",function(){return ja});d.d(V,"skip",function(){return C});d.d(V,"skipWhile",function(){return pa});d.d(V,"SWI",function(){return Z});d.d(V,"take",function(){return qa});d.d(V,"takeWhile",function(){return ya});d.d(V,"TW",function(){return Ka});d.d(V,"where",function(){return Da});d.d(V,"first",function(){return la});d.d(V,"FT",function(){return ma});d.d(V,"firstOrDefault",function(){return Ea});
d.d(V,"FDT",function(){return ta});d.d(V,"last",function(){return Ga});d.d(V,"LT",function(){return oa});d.d(V,"lastOrDefault",function(){return sa});d.d(V,"LDT",function(){return Ha});d.d(V,"cast",function(){return bb});d.d(V,"any",function(){return Ya});d.d(V,"AT",function(){return ua});d.d(V,"all",function(){return Ma});d.d(V,"count",function(){return Ca});d.d(V,"Ct",function(){return Va});d.d(V,"CT",function(){return Za});d.d(V,"aggregate",function(){return Db});d.d(V,"AgS",function(){return Lb});
d.d(V,"AgSS",function(){return yb});d.d(V,"concat",function(){return Bc});d.d(V,"repeat",function(){return tb});d.d(V,"zip",function(){return Mb});d.d(V,"orderBy",function(){return Hb});d.d(V,"OBc",function(){return vb});d.d(V,"orderByDescending",function(){return Xb});d.d(V,"OBdc",function(){return Uc});d.d(V,"thenBy",function(){return hb});d.d(V,"TBc",function(){return Zb});d.d(V,"thenByDescending",function(){return Fc});d.d(V,"TBDc",function(){return ob});d.d(V,"toList",function(){return ac});
d.d(V,"toArray",function(){return pb});d.d(V,"toDictionary",function(){return nb});d.d(V,"TD",function(){return Tb});d.d(V,"SumS",function(){return Ub});d.d(V,"MinS",function(){return hc});d.d(V,"MaxS",function(){return Wb});d.d(V,"empty",function(){return fd});const K=fc=>new e(fc),X=fc=>new u(fc),P=(fc,bc)=>new I(fc,bc,null),ea=(fc,bc)=>new I(fc,null,bc),ia=(fc,bc)=>new H(fc,null,bc),ja=(fc,bc)=>new H(fc,bc,null),C=(fc,bc)=>new L(fc,bc),pa=(fc,bc)=>new E(fc,bc,null),Z=(fc,bc)=>new E(fc,null,bc),
qa=(fc,bc)=>new aa(fc,bc),ya=(fc,bc)=>new Q(fc,bc,null),Ka=(fc,bc)=>new Q(fc,null,bc),Da=(fc,bc)=>new O(fc,bc),la=fc=>{fc=fc.$$ge();if(!fc.$$mn())throw Error.argumentNull("source");return fc.$$cu()},ma=(fc,bc)=>{fc=fc.$$ge();do if(!fc.$$mn())throw Error.argumentNull("source");while(!bc(fc.$$cu()));return fc.$$cu()},Ea=(fc,bc=null)=>{fc=fc.$$ge();return fc.$$mn()?fc.$$cu():bc},ta=(fc,bc,cc=null)=>{fc=fc.$$ge();do if(!fc.$$mn())return cc;while(!bc(fc.$$cu()));return fc.$$cu()},Ga=fc=>{fc=fc.$$ge();
if(!fc.$$mn())throw Error.argumentNull("source");let bc;do bc=fc.$$cu();while(fc.$$mn());return bc},oa=(fc,bc)=>{fc=fc.$$ge();for(var cc;(cc=fc.$$mn())&&!bc(fc.$$cu()););if(!cc)throw Error.argumentNull("source");for(cc=fc.$$cu();fc.$$mn();)bc(fc.$$cu())&&(cc=fc.$$cu());return cc},sa=(fc,bc=null)=>{fc=fc.$$ge();if(!fc.$$mn())return bc;do bc=fc.$$cu();while(fc.$$mn());return bc},Ha=(fc,bc,cc=null)=>{fc=fc.$$ge();let kb;for(;(kb=fc.$$mn())&&!bc(fc.$$cu()););if(!kb)return cc;for(cc=fc.$$cu();fc.$$mn();)bc(fc.$$cu())&&
(cc=fc.$$cu());return cc},bb=fc=>new v(fc),Ya=fc=>fc.$$ge().$$mn(),ua=(fc,bc)=>{for(const cc of fc)if(bc(cc))return!0;return!1},Ma=(fc,bc)=>{for(const cc of fc)if(!bc(cc))return!1;return!0},Ca=fc=>{let bc=0;for(const cc of fc)bc++;return bc},Va=fc=>{let bc=0;for(const cc of fc)bc++;return bc},Za=(fc,bc)=>{fc=fc.$$ge();let cc=0;for(;fc.$$mn();)bc(fc.$$cu())&&cc++;return cc},Db=(fc,bc)=>{fc=fc.$$ge();if(!fc.$$mn())throw Error.invalidOperation("source contains no elements");let cc=fc.$$cu();for(;fc.$$mn();)cc=
bc(cc,fc.$$cu());return cc},Lb=(fc,bc,cc)=>{for(const kb of fc)bc=cc(bc,kb);return bc},yb=(fc,bc,cc,kb)=>{for(const ab of fc)bc=cc(bc,ab);return kb(bc)},Bc=(fc,bc)=>new A(fc,bc),tb=(fc,bc)=>new F(fc,bc),Mb=(fc,bc,cc)=>new T(fc,bc,cc),Hb=(fc,bc)=>new D(fc,bc,null,null,!1),vb=(fc,bc,cc)=>new D(fc,bc,cc,null,!1),Xb=(fc,bc)=>new D(fc,bc,null,null,!0),Uc=(fc,bc,cc)=>new D(fc,bc,cc,null,!0),hb=(fc,bc)=>new D(fc,bc,null,fc,!1),Zb=(fc,bc,cc)=>new D(fc,bc,cc,fc,!1),Fc=(fc,bc)=>new D(fc,bc,null,fc,!0),ob=(fc,
bc,cc)=>new D(fc,bc,cc,fc,!0),ac=fc=>{const bc=new m.a;for(const cc of fc)bc.add(cc);return bc},pb=fc=>ac(fc).toArray(),nb=(fc,bc)=>{const cc=new (d(14).ScriptSharpLegacyMap);for(const kb of fc)cc.add(bc(kb),kb);return cc},Tb=(fc,bc,cc)=>{const kb=new (d(14).ScriptSharpLegacyMap);for(const ab of fc)kb.add(bc(ab),cc(ab));return kb},Ub=(fc,bc)=>{let cc=0;for(const kb of fc)cc+=bc(kb);return cc},hc=(fc,bc)=>{let cc=Number.POSITIVE_INFINITY;for(const kb of fc)fc=bc(kb),fc<cc&&(cc=fc);return cc},Wb=(fc,
bc)=>{let cc=Number.NEGATIVE_INFINITY;for(const kb of fc)fc=bc(kb),fc>cc&&(cc=fc);return cc},fd=()=>new w},function(J,V,d){d.r(V);d.d(V,"ContinuableTask$1",function(){return h});J=d(0);d=d(4);class h extends d.a{constructor(){super();this._parent=this.UXe=this.Jpd=null}execute(){this.Jpd?this.ylc(this.Jpd(this._parent)):this.ylc(this.UXe(this._parent,this.Yn));return!0}static C(e,m){const r=new h;r.Jpd=e;r._parent=m;return r}static CO(e,m,r){const v=new h;v.UXe=e;v.Yn=m;v._parent=r;return v}}Object(J.a)(h,
"ContinuableTask$1",d.a,[])},function(J,V,d){J=d(0);var h=d(11);class e{constructor(r,v,A){this.UJ=!1;this.vjb=r;this.wLb=v;this.Yn=A}get disposed(){return this.UJ}xoc(){this.disposed||(this.vjb?this.vjb():this.wLb(this.Yn))}dispose(){this.UJ=!0}}Object(J.a)(e,"CancellationTokenRegistration",null,[106]);d.d(V,"a",function(){return m});class m{constructor(r){this.tRb=null;this.a9e=!1;this.EKh=r}get IDa(){return this.a9e}get Rki(){return this.EKh}R(r){return this.register(r)}register(r){r=new e(r,null,
null);this.qdh(r);return r}RO(r,v){r=new e(null,r,v);this.qdh(r);return r}qdh(r){this.IDa?r.xoc():this.tRb=h.a(this.tRb,r)}cancel(r){if(!this.Rki)throw Error.invalidOperation("CanBeCanceled is false");if(!this.IDa&&(this.a9e=!0,r&&this.tRb))for(const v of this.tRb)v.xoc()}static uGc(){return Error.create("OperationCanceledException: Task canceled",{["$$canceled"]:!0})}static get none(){return m.kTh}static Stg(r){return r[m.nPi]}}m.nPi="$$canceled";m.kTh=new m(!1);Object(J.a)(m,"CancellationToken",
null,[])},function(J,V,d){d.d(V,"a",function(){return h});d.d(V,"b",function(){return e});const h=m=>{const r=[];for(const v of m)r.push(v);return Error.create("AggregateException: Aggregate exceptions",{["Exceptions"]:r})},e=m=>{const r=[];for(const v of m)r.push(v);return Error.create("AggregateException: Aggregate exceptions",{["Exceptions"]:r})}},function(J,V,d){d.d(V,"a",function(){return h});J=d(0);class h{constructor(e){this.Ph=-1;this.$$cu=this.get_current;this.$$mn=this.moveNext;this.$$rst=
this.reset;this.zH=e}get_current(){if(-1===this.Ph||this.Ph>=this.zH.length)throw Error.invalidOperation();return this.zH[this.Ph]}moveNext(){this.Ph++;return this.Ph<this.zH.length}reset(){this.Ph=-1}next(){this.Ph++;return this.Ph<this.zH.length?{done:!1,value:this.zH[this.Ph]}:{done:!0,value:void 0}}}Object(J.a)(h,"ArrayEnumerator$1",null,[142])},function(J,V,d){d.d(V,"a",function(){return h});const h=(e,m)=>e?(e.push(m),e):[m]},function(J,V,d){d.r(V);d.d(V,"CompletableTask$1",function(){return e});
J=d(0);V=d(4);var h=d(9);class e extends V.a{constructor(){super()}SEsE(m){this.bhb(h.a(m))}SEsA(m){this.bhb(h.b(m))}SE(m){this.bhb(m)}Dg(m){this.ylc(m);this.KC(!0)}}Object(J.a)(e,"CompletableTask$1",V.a,[])},function(J,V,d){d.d(V,"a",function(){return h});const h=(e,m,r)=>{r=`$$d_${r}`;null==e[r]&&(e[r]=m.bind(e));return e[r]}},function(J,V,d){d.r(V);d.d(V,"ScriptSharpLegacyMap",function(){return v});J=d(0);var h=d(13),e=d(21),m=d(15),r=d(6);class v{constructor(){this.qp=new Map;this.getEnumerator=
this.N_d}$$ge(){return r.select(r.fromIterator(Object(h.a)(this.qp,this.qp.entries,"entries")),A=>new m.a(A[0],A[1])).$$ge()}N_d(){return this.$$ge()}get count(){return this.qp.size}get keys(){return r.fromIterator(Object(h.a)(this.qp,this.qp.keys,"keys"))}get values(){return r.fromIterator(Object(h.a)(this.qp,this.qp.values,"values"))}Akvp(A){if(this.qp.has(A.key))throw Error.create("DuplicateKeyException");this.qp.set(A.key,A.value)}ga(A){const {value:w,returnValue:y}=this.Rf(A,null);if(!y)throw Error.create("KeyNotFoundException");
return w}$(A,w){this.qp.set(A,w);return w}add(A,w){if(this.qp.has(A))throw Error.create("DuplicateKeyException");this.qp.set(A,w)}Jb(A){return this.qp.has(A)}remove(A){return this.qp.delete(A)}Rf(A,w=null){return this.qp.has(A)?{returnValue:!0,value:this.qp.get(A)}:{returnValue:!1,value:w}}[Symbol.iterator](){return Object(e.a)(this.getEnumerator())}}Object(J.a)(v,"ScriptSharpLegacyMap",null,[143,141,1])},function(J,V,d){d.d(V,"a",function(){return h});J=d(0);class h{constructor(e,m){this.value=m;
this.key=e}}Object(J.a)(h,"KeyValuePair",null,[])},function(J,V,d){d.r(V);d.d(V,"CompletableTask",function(){return e});J=d(0);V=d(2);var h=d(9);class e extends V.Task{constructor(){super()}SEsE(m){this.bhb(h.a(m))}SEsA(m){this.bhb(h.b(m))}SE(m){this.bhb(m)}Dg(){this.KC(!0)}}Object(J.a)(e,"CompletableTask",V.Task,[])},function(J,V,d){J=d(0);var h=d(10);class e{constructor(r){this.Ph=-1;this.zH=r}get_current(){if(-1===this.Ph||this.Ph>=this.zH.length)throw Error.invalidOperation();return this.zH[this.Ph]}moveNext(){this.Ph++;
return this.Ph<this.zH.length}reset(){this.Ph=-1}next(){this.Ph++;return this.Ph<this.zH.length?{done:!1,value:this.zH[this.Ph]}:{done:!0,value:void 0}}}Object(J.a)(e,"ArrayEnumerator",null,[0]);d.d(V,"a",function(){return m});class m{constructor(r=null){this.$$ge=this.$$lge;this.getEnumerator=this.N_d;this.zB=r?r:[]}$$lge(){return new h.a(this.zB)}N_d(){return new e(this.zB)}[Symbol.iterator](){return this.zB[Symbol.iterator]()}get count(){return this.zB.length}add(r){this.zB.push(r)}push(...r){for(const v of r)this.zB.push(v)}clear(){this.zB=
[]}contains(r){return Array.contains(this.zB,r)}remove(r){return this.contains(r)?(Array.remove(this.zB,r),!0):!1}indexOf(r){return Array.indexOf(this.zB,r)}removeAt(r){if(r>=this.count)throw Error.argumentOutOfRange("index");Array.removeAt(this.zB,r)}ga(r){if(r>=this.count)throw Error.argumentOutOfRange("index");return this.zB[r]}$(r,v){if(r>=this.count)throw Error.argumentOutOfRange("index");return this.zB[r]=v}addRange(r){for(const v of r)this.add(v)}insert(r,v){if(r>this.count)throw Error.argumentOutOfRange("index");
Array.insert(this.zB,r,v)}vSc(r,v){if(r>this.count)throw Error.argumentOutOfRange("index");for(const A of v)Array.insert(this.zB,r++,A)}toArray(){return Array.clone(this.zB)}sort(){this.zB.sort()}Sc(r){this.zB.sort((v,A)=>r(v,A))}}Object(J.a)(m,"List",null,[1758,141,1])},function(J,V,d){d(19);J.exports=d(20)},function(J,V,d){d.p=function(){function h(){for(var v=document.getElementsByTagName("script"),A=0;A<v.length;A++){var w=e(v[A].src);if(w)return w}return null}function e(v){return v.toLowerCase().endsWith("/ppteditds.precore.js")?
v.substring(0,v.lastIndexOf("/")+1):null}var m=document.currentScript,r=null;if(m)r=e(m.src.split("?")[0]);else{if("undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope)return d.p;r=h()}if(r)return r;throw"Could not locate webpack public path";}()},function(J,V,d){d.r(V);var h=d(22);const e=(u,D)=>{if(null!=D&&!Object(h.a)(u,D))throw Error.create(Sys.Res.argumentType);return D};var m=d(2);J=d(0);var r=d(4),v=d(1);class A{constructor(){this.aNa=v.a.default}S(u){u=m.Task.Create(u);
u.Start$Scheduler(this.aNa);return u}SC(u,D){u=m.Task.Create(u);D.IDa?u.w0():u.Start$Scheduler(this.aNa);return u}SO(u,D){u=m.Task.Create$object(u,D);u.Start$Scheduler(this.aNa);return u}SOC(u,D,F){u=m.Task.Create$object(u,D);F.IDa?u.w0():u.Start$Scheduler(this.aNa);return u}SR(u){u=r.a.C(u);u.Start$Scheduler(this.aNa);return u}SRC(u,D){u=r.a.C(u);D.IDa?u.w0():u.Start$Scheduler(this.aNa);return u}SRO(u,D){u=r.a.CO(u,D);u.Start$Scheduler(this.aNa);return u}SROC(u,D,F){u=r.a.CO(u,D);F.IDa?u.w0():u.Start$Scheduler(this.aNa);
return u}}Object(J.a)(A,"TaskFactory",null,[]);class w extends v.a{constructor(){super()}cEe(u){window.setTimeout(()=>{this.ETe(u)},0)}}Object(J.a)(w,"DefaultTaskScheduler",v.a,[]);J=function(u){function D(I){if(F[I])return F[I].exports;var H=F[I]={i:I,l:!1,exports:{}};u[I].call(H.exports,H,H.exports,D);H.l=!0;return H.exports}var F={};D.m=u;D.c=F;D.d=function(I,H,L){D.o(I,H)||Object.defineProperty(I,H,{enumerable:!0,get:L})};D.r=function(I){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(I,
Symbol.toStringTag,{value:"Module"});Object.defineProperty(I,"__esModule",{value:!0})};D.t=function(I,H){H&1&&(I=D(I));if(H&8||H&4&&"object"===typeof I&&I&&I.caa)return I;var L=Object.create(null);D.r(L);Object.defineProperty(L,"default",{enumerable:!0,value:I});if(H&2&&"string"!=typeof I)for(var E in I)D.d(L,E,function(aa){return I[aa]}.bind(null,E));return L};D.n=function(I){var H=I&&I.caa?function(){return I["default"]}:function(){return I};D.d(H,"a",H);return H};D.o=function(I,H){return Object.prototype.hasOwnProperty.call(I,
H)};D.p="";return D(D.s=78)}({100:function(u,D,F){function I(){return E}function H(aa,Q,O){E.fireEvent({level:aa,category:Q,message:O})}function L(aa,Q,O){H(0,aa,function(){return"".concat(Q,": ").concat(O instanceof Error?O.message:"")})}F.d(D,"c",function(){return I});F.d(D,"b",function(){return H});F.d(D,"a",function(){return L});var E=function(){var aa=[];return{fireEvent:function(Q){aa.forEach(function(O){return O(Q)})},addListener:function(Q){Q&&aa.push(Q)}}}()},101:function(u,D,F){function I(aa,
Q,O){return{name:aa,dataType:1,value:Q,classification:O?O:4}}function H(aa,Q,O){return{name:aa,dataType:2,value:Q,classification:O?O:4}}function L(aa,Q,O){return{name:aa,dataType:3,value:Q,classification:O?O:4}}function E(aa,Q,O){return{name:aa,dataType:0,value:Q,classification:O?O:4}}F.d(D,"a",function(){return I});F.d(D,"c",function(){return H});F.d(D,"b",function(){return L});F.d(D,"d",function(){return E})},102:function(u,D,F){function I(){return"undefined"===typeof performance||"undefined"===
typeof performance.now?0:performance.now()}function H(L){if(null!==L)return L}F.d(D,"a",function(){return I});F.d(D,"b",function(){return H})},103:function(u,D,F){F.d(D,"a",function(){return H});var I=F(101),H=function(){function L(){this.name="Sampler";this.sampleRate=.02}L.prototype.N0f=function(E,aa){if("string"!==typeof aa||4>aa.length)return!1;for(var Q=5381,O=0;O<aa.length;O++)Q=(Q<<5)+Q+aa.charCodeAt(O);this.tkc=(Q>>>0)%1E3/1E3;this.Wjh=E;return!0};L.prototype.U6k=function(E){0<=E&&1>=E&&(this.sampleRate=
E)};L.prototype.axg=function(){return void 0===this.tkc||this.tkc<this.sampleRate};L.prototype.LX=function(E){var aa=E.eventFlags.samplingPolicy;if(void 0===this.tkc||void 0===aa)return!0;if(1===aa)return this.axg()?(this.eEf(E,this.sampleRate,this.tkc),!0):!1;if(2===aa)return!1;this.eEf(E,1,this.tkc);return!0};L.prototype.eEf=function(E,aa,Q){E.eventContract||(E.eventContract={name:"",dataFields:[]});E=E.eventContract.dataFields;E.push(Object(I.b)("Event.SampleRate",aa));E.push(Object(I.b)("Session.SamplingValue",
Q));this.Wjh&&E.push(Object(I.d)("Session.SamplingKey",this.Wjh));E.push(Object(I.a)("Session.MeasuresEnabled",this.axg()))};return L}()},104:function(u,D,F){function I(){I=Object.assign||function(H){for(var L,E=1,aa=arguments.length;E<aa;E++){L=arguments[E];for(var Q in L)Object.prototype.hasOwnProperty.call(L,Q)&&(H[Q]=L[Q])}return H};return I.apply(this,arguments)}F.d(D,"a",function(){return I})},105:function(u,D,F){function I(K){if(!K.name)throw Error("Event is missing a name");var X=aa(K.dataFields);
X={eventName:K.name,dataFields:X,eventFlags:{}};1===K.samplingPolicy&&(X.eventFlags={samplingPolicy:1});return X}function H(K){if(!K.name)throw Error("Event is missing a name");var X=aa(K.dataFields),P={eventName:K.name,dataFields:X,eventFlags:{},telemetryProperties:{dnmInterval:K.dnmInterval,dnmAllowedPartA:[]}};K.dnmAllowedPartA&&K.dnmAllowedPartA.forEach(function(ea){ea&&ea&&P.telemetryProperties.dnmAllowedPartA.push(ea)});return P}function L(K){if(!K.name)throw Error("Event is missing a name");
null==K.succeeded&&(K.succeeded=void 0);if(null==K.durationMs||isNaN(K.durationMs))K.durationMs=0;if(null==K.count||isNaN(K.count))K.count=1;null==K.aggMode&&(K.aggMode=0);var X=Math.floor(1E3*K.durationMs),P=aa(K.dataFields);X=O.a.mtb({Rhi:K.CV||void 0,duration:X,count:K.count,aggMode:K.aggMode,success:K.succeeded});return{eventName:K.name,eventContract:{name:O.a.lQd,dataFields:X},dataFields:P,eventFlags:{}}}function E(K){if(!K.name)throw Error("Event is missing a name");null==K.succeeded&&(K.succeeded=
void 0);if(null==K.durationMs||isNaN(K.durationMs))K.durationMs=0;var X=Math.floor(1E3*K.durationMs);null==K.dataFields&&(K.dataFields=[]);var P=aa(K.dataFields),ea=O.b.mtb({id:null==K.actionId?void 0:K.actionId,name:null==K.actionName?void 0:K.actionName,commandSurface:null==K.commandSurface?void 0:K.commandSurface,parentName:null==K.parentName?void 0:K.parentName,triggerMethod:null==K.triggerMethod?void 0:K.triggerMethod,timeOffsetMs:null==K.timeOffsetMs?void 0:K.timeOffsetMs});P.push.apply(P,ea);
X=O.a.mtb({duration:X,count:1,aggMode:0,success:K.succeeded});return{eventName:K.name,eventContract:{name:O.a.lQd,dataFields:X},dataFields:P,eventFlags:{}}}function aa(K){var X=[];if(K)for(var P=0;P<K.length;P+=1)X.push.apply(X,Q(K[P]));return X}function Q(K,X){K.name||(K.name="DataFieldNameIsMissing");var P=null!=K.string?2:null!=K.bool?1:null==K.int64||isNaN(K.int64)?null==K.double||isNaN(K.double)?null!=K.contract?6:null==K.date||isNaN(K.date)?0:5:4:3;X=X?X+"."+K.name:K.name;switch(P){case 0:return[];
case 1:return[T.a(X,K.bool)];case 2:return[T.d(X,K.string)];case 3:return[T.c(X,Math.floor(K.int64))];case 4:return[T.b(X,K.double)];case 5:return[T.d(X,(new Date(K.date)).toISOString())];case 6:K=K.contract;P=[];if(K.dataFields)for(var ea=0;ea<K.dataFields.length;ea+=1)P.push.apply(P,Q(K.dataFields[ea],X));return P;default:throw Error(P);}}F.d(D,"c",function(){return I});F.d(D,"b",function(){return H});F.d(D,"a",function(){return L});F.d(D,"e",function(){return E});F.d(D,"d",function(){return aa});
var O=F(106),T=F(101);F(107)},106:function(u,D,F){function I(T,K,X,P){X&&P.push(Object(E.d)("".concat(T?T+"."+K:K),X))}function H(T,K,X,P){"boolean"===typeof X&&P.push(Object(E.a)("".concat(T?T+"."+K:K),X))}function L(T,K,X,P){"number"===typeof X&&P.push(Object(E.c)("".concat(T?T+"."+K:K),X))}F.d(D,"a",function(){return Q});F.d(D,"b",function(){return O});var E=F(101),aa={mtb:function(T){var K=[];L("Activity.Result","Code",T.code,K);I("Activity.Result","Type",T.type,K);L("Activity.Result","Tag",T.tag,
K);H("Activity.Result","IsExpected",T.isExpected,K);K.push(Object(E.d)("zC.Activity.Result","Office.System.Result"));return K}},Q={lQd:"Office.System.Activity",mtb:function(T){var K=[];I("Activity","CV",T.Rhi,K);L("Activity","Duration",T.duration,K);L("Activity","Count",T.count,K);L("Activity","AggMode",T.aggMode,K);H("Activity","Success",T.success,K);T.result&&K.push.apply(K,aa.mtb(T.result));K.push(Object(E.d)("zC.Activity",this.lQd));return K}},O={mtb:function(T){var K=[];L("UserAction","Id",T.id,
K);I("UserAction","Name",T.name,K);I("UserAction","CommandSurface",T.commandSurface,K);I("UserAction","ParentName",T.parentName,K);I("UserAction","TriggerMethod",T.triggerMethod,K);L("UserAction","TimeOffsetMs",T.timeOffsetMs,K);return K}}},107:function(u,D,F){F.d(D,"a",function(){return I});var I;(function(H){H[H.Error=10]="Error";H[H.Warning=15]="Warning";H[H.Info=50]="Info";H[H.Verbose=100]="Verbose";H[H.Spam=200]="Spam"})(I||(I={}))},108:function(u,D,F){function I(ia){return ia?[H,L,E,aa,Q,T,
O].map(function(ja){return ja(ia)}):[]}function H(ia){return{name:"App",contract:{name:"App",dataFields:[K("Name",ia.name),K("Platform",ia.platform),K("Version",ia.version)]}}}function L(ia){return{name:"Session",contract:{name:"Session",dataFields:[K("Id",ia.sessionId),K("EcsETag",ia.flightsImpressionId)]}}}function E(ia){return{name:"Release",contract:{name:"Release",dataFields:[K("AudienceGroup",ia.audienceGroup)]}}}function aa(ia){return{name:"Browser",contract:{name:"Browser",dataFields:[K("Name",
ia.browserName),K("Version",ia.browserVersion)]}}}function Q(ia){return{name:"Culture",contract:{name:"Culture",dataFields:[K("UiLanguage",ia.appLanguage)]}}}function O(ia){return{name:"User",contract:{name:"User",dataFields:[K("PrimaryIdentityHash",ia.loggableUserId),K("PrimaryIdentitySpace",ia.loggableUserIdSpace),K("TenantId",ia.omsTenantId),X("IsAnonymous",ia.isAnonymousUser)]}}}function T(ia){return{name:"WAC",contract:{name:"WAC",dataFields:[K("Host",ia.host),K("ServerDocId",ia.serverDocId),
K("Datacenter",ia.datacenter),X("IsSynthetic",ia.isSynthetic),X("IsBusinessUser",ia.isBusinessUser),X("IsEdu",ia.isEduUser),K("ApplicationMode",ia.applicationMode),K("ApplicationModeExtended",ia.applicationModeExtended),K("BrowserLanguage",ia.browserLanguage),K("ContentLanguage",ia.contentLanguage),K("OsVersion",ia.osVersion),K("Ring",ia.ring),K("UiHost",ia.uiHost),K("SessionOrigin",ia.sessionOrigin),K("UiHostIntegrationType",ia.uiHostIntegrationType)]}}}function K(ia,ja){return null==ja?{name:ia,
string:P}:{name:ia,string:ja}}function X(ia,ja){return null==ja?{name:ia,bool:ea}:{name:ia,bool:ja}}F.d(D,"a",function(){return I});var P="",ea=!1},109:function(u,D,F){function I(K){var X={eventName:K.eventName,eventFlags:K.eventFlags||{},telemetryProperties:K.telemetryProperties?Object(H.a)({},K.telemetryProperties):{},dataFields:K.dataFields?K.dataFields.slice():[],timestamp:K.timestamp||(new Date).getTime()};K.eventContract&&(X.eventContract={name:K.eventContract.name,dataFields:K.eventContract.dataFields.slice()});
return X}F.d(D,"a",function(){return T});var H=F(104),L=F(110),E=F(112),aa=F(100),Q=F(111),O=F(101),T=function(){function K(X,P,ea){var ia,ja,C;this.wJb=[];this.persistentDataFields=[];this.vad=[];this.r7=[];this.config=ea||{};X&&(this.wJb=X.wJb,(ia=this.persistentDataFields).push.apply(ia,X.persistentDataFields),this.config=Object(H.a)(Object(H.a)({},X.getConfig()),this.config),(ja=this.vad).push.apply(ja,X.vad));P&&(C=this.persistentDataFields).push.apply(C,P)}K.prototype.fDf=function(X,P){X.push(Object(O.c)("EventContent.Type",
P))};K.prototype.sendTelemetryEvent=function(X){var P=I(X),ea=P.telemetryProperties;ea.nexusTenantToken=-1;ea.ariaTenantToken||Object(L.a)(P.eventName,ea)||ea.ariaTenantToken?this.Zgd(P,1):Object(aa.b)(0,0,function(){return"No tenant token: "+X.eventName})};K.prototype.Elh=function(X){X=I(X);var P=X.telemetryProperties,ea=P.customerContentVersion;if(!ea||2<ea)P.customerContentVersion=2;P.ariaTenantToken=void 0;P.nexusTenantToken=void 0;P.dnmToken=void 0;this.fDf(X.dataFields,2);return this.Zgd(X,
2)};K.prototype.sendDirectNumericEvent=function(X){var P=I(X);X=P.telemetryProperties;X.dnmToken||Object(L.a)(P.eventName,X)||X.dnmToken?(this.fDf(P.dataFields,1),this.Zgd(P,3)):Object(aa.b)(0,0,function(){return"No dnm token: "+P.eventName})};K.prototype.Zgd=function(X,P){if(2!==P&&(X.telemetryProperties.customerContentVersion||X.telemetryProperties.customerContentType))Object(aa.b)(0,0,function(){return"Customer content"});else{try{if(0===this.wJb.length){this.config.gFl&&1E3>this.r7.length?this.r7.push([X,
P]):Object(aa.b)(1,0,function(){return"No telemetry sinks are attached."});return}this.processTelemetryEvent(X,P)}catch(ea){Object(aa.a)(0,"SendTelemetryEvent",ea);return}try{this.wJb.forEach(function(ea){3===P||2===P?ea.Llh&&ea.Llh(X,P):ea.sendTelemetryEvent(X)})}catch(ea){}}};K.prototype.processTelemetryEvent=function(X,P){var ea,ia,ja;X.dataFields&&(null===(ja=X.dataFields)||void 0===ja?void 0:ja.unshift(Object(O.d)("OTelJS.Version",Q.a)),3!==P&&this.persistentDataFields&&(ea=X.dataFields).unshift.apply(ea,
this.persistentDataFields));0<this.vad.length&&(P=X.eventContract||{name:"",dataFields:[]},(ia=P.dataFields).push.apply(ia,this.vad),X.eventContract=P);this.config.QIi||Object(E.a)(X)};K.prototype.G3h=function(X){this.wJb.push(X);this.jLc()};K.prototype.jLc=function(){var X=this.r7;this.r7=[];if(0<this.wJb.length)for(var P=0;P<X.length;P++){var ea=X[P];this.Zgd(ea[0],ea[1])}};K.prototype.Ooh=function(X,P){Object(L.b)(X,{ariaTenantToken:P,nexusTenantToken:void 0})};K.prototype.setDNMToken=function(X,
P){Object(L.b)(X,{dnmToken:P})};K.prototype.getConfig=function(){return this.config};return K}()},110:function(u,D,F){function I(Q,O){Q.substring(0,7)==="Office"+E&&Q[Q.length-1]!==E?aa[Q]?(O.ariaTenantToken&&(aa[Q].ariaTenantToken=O.ariaTenantToken),O.dnmToken&&(aa[Q].dnmToken=O.dnmToken)):aa[Q]=O:Object(L.b)(0,0,function(){return"Namespace: ".concat(Q)})}function H(Q,O){for(var T=Q.length;0<T;){var K=Q.substr(0,T);if(aa[K])return Q=aa[K],O.ariaTenantToken=Q.ariaTenantToken,O.dnmToken=Q.dnmToken,
!0;T=Q.lastIndexOf(E,T-1)}return!1}F.d(D,"b",function(){return I});F.d(D,"a",function(){return H});var L=F(100),E=".",aa={}},111:function(u,D,F){F.d(D,"a",function(){return I});var I="4.13.6"},112:function(u,D,F){function I(T){var K=T.eventName;if(!K||K.length>aa||!Q.test(K))throw Error("Invalid eventName");if(K=T.eventContract){if(K.name&&!O.test(K.name))throw Error("Invalid eventContract");H(K.dataFields)}H(T.dataFields)}function H(T){T&&T.forEach(function(K){if("string"!==typeof K.name||!O.test(K.name))throw Error("Invalid dataField name");
if(2===K.dataType&&(K=K.value,"number"!==typeof K||!isFinite(K)||Math.floor(K)!==K||K<E||K>L))throw Error("Invalid integer ".concat(JSON.stringify(K)));})}F.d(D,"a",function(){return I});var L=9007199254740991,E=-L,aa=98,Q=/^Office(\.[A-Z][a-zA-Z0-9]*){2,}$/,O=/^[a-zA-Z0-9_\.]{1,95}$/},113:function(u,D,F){F.d(D,"a",function(){return I});F.d(D,"b",function(){return H});var I=[{namespace:"Office.Online",iu:"79b56d2f6f2444f1a3d7f7c7f12bcc0c-f47f5fe6-ed89-42f6-8a43-cea0f5930b17-7407"},{namespace:"Office.Word.Online.Data",
iu:"7e7959aac92e41d6892c69a87259ed58-de5c63ef-10f5-45e1-bef2-d23e9cac2fab-6830"},{namespace:"Office.Excel.Online.Data",iu:"011776870b754a649aedc9456ac07a97-6bd8247c-11d3-4599-b599-ec9ef6d401f6-6722"},{namespace:"Office.PowerPoint.Online.Data",iu:"35612b11d234460da5c673d7b172fd93-f8762c6b-96cb-4e60-87fa-015aac0c2ff1-7212"},{namespace:"Office.OneNote.Online.Data",iu:"86258c80efed47d9b34bf77fc663b381-af82a060-b49f-448b-baf0-956ba7709592-7634"},{namespace:"Office.Visio.Online.Data",iu:"77fd25a525d24b7f9b924307de0cc70f-5f2b6ec0-f1d2-40dd-b875-e6bd2849e1eb-7539"},
{namespace:"Office.Shared.Online.Data",iu:"4ad8b2b2029e481fb82edb7aac29de59-94494dd8-b684-4f92-ab7f-6b414eb77798-7917"},{namespace:"Office.Word.Online",iu:"ff7e2f12a4be407096fc01eeb760eda3-eeeb63cf-35d9-4734-ab45-66a873412359-7045"},{namespace:"Office.Excel.Online",iu:"fad3bd1d8e4b4c06894bd7bac80e4f02-67df67b4-f1fd-4ecd-9d55-4d41540b1757-7724"},{namespace:"Office.PowerPoint.Online",iu:"b664cab4b3f24a739be75b93b026749e-65c206a3-a985-48b4-8b50-36c56c3ce309-7201"},{namespace:"Office.OneNote.Online",
iu:"1705ef36a51840648341da866d62baf8-ddbcd60b-4ce4-48da-96be-ad5f28b48954-8035"},{namespace:"Office.Visio.Online",iu:"a9b6cb604fe942a89c8671aab85364f6-af0f81b1-c5ce-419a-82d5-af38c33ebea3-7250"},{namespace:"Office.Shared.Online",iu:"d034371e26194a76a187c7108b3837ca-731725e8-1dc7-4eca-a754-b09c9d2b8dd5-6502"},{namespace:"Office.Word.Online.Health",iu:"e064ef4d9cdb454d9eddb2f7f7a94c83-89a6d9df-7218-4efd-bcd4-16ea059deea2-7672"},{namespace:"Office.Excel.Online.Health",iu:"e76e8055912d482eb56ea5dad2fd5a97-5552f2bb-d1eb-4843-95d7-3019215328a0-6899"},
{namespace:"Office.PowerPoint.Online.Health",iu:"706f939c0d24440ba8dfb0838ed33611-d60b1956-db23-4410-a59d-e7fa08d4217f-7388"},{namespace:"Office.OneNote.Online.Health",iu:"c6393e4ed4b94e3baf9a46aa6585dce0-c1b3b0c6-b44c-4121-8eae-311d31e67bb6-7176"},{namespace:"Office.Visio.Online.Health",iu:"c4999163c49d49c99a1649b404873d24-a62a394b-ad47-45f0-92fa-fd4085dc8bb3-7324"},{namespace:"Office.Shared.Online.Health",iu:"2800319cefba4489867c1ff30d41e7e1-ea67d761-9485-4d25-bc39-f3144e34b773-6869"},{namespace:"Office.Telemetry",
iu:"f998cc5ba4d448d6a1e8e913ff18be94-dd122e0a-fcf8-4dc5-9dbb-6afac5325183-7405"},{namespace:"Office.System",iu:"cd836626611c4caaa8fc5b2e728ee81d-3b6d6c45-6377-4bf5-9792-dbf8e1881088-7521"},{namespace:"Office.TellMe",iu:"31d9dd3e4c7046a696537586281d7ed1-06d11dd6-a946-4281-8ac3-a7c2ab4776f5-7063"},{namespace:"Office.Voice",iu:"9783945ebc2b468fbb8a2890cdab903b-787355a5-74c8-4a89-b06a-9c82635d75fa-7162"},{namespace:"Office.Insights",iu:"250a372c4a854d8fb120ef0366f9410c-dd39bcd8-3b38-4c6c-9f8d-3821e5c28b47-7487"},
{namespace:"Office.Graphics",iu:"cfcfdb91c68c4329bb8b7cb7babb3cf7-e082c2f2-ef1d-427a-ac4d-b0b700afe7a7-7655"},{namespace:"Office.AugLoop",iu:"3de4087d4de34817b1c376e3d1e6e293-983c4292-5ba9-485a-ab10-9797863c788b-6770"},{namespace:"Office.FileIO",iu:"d2b065c5ae634beb9cec4813140e22da-eda42ada-ffd9-4e26-92a1-e3b440eaf8bf-7717"},{namespace:"Office.Sandbox",iu:"1cd66059dc1d41f1887e3770ea8ba967-f1d0108c-8535-4cf9-bf23-ec8227f6afa7-6999"},{namespace:"Office.UX",iu:"c4388c977297413bb054bad1acf0ade1-cc58e53e-f5a4-4f37-b0d2-9a8079e34420-6879"},
{namespace:"Office.Extensibility",iu:"db334b301e7b474db5e0f02f07c51a47-a1b5bc36-1bbe-482f-a64a-c2d9cb606706-7439"}],H=[{namespace:"Office.DNM.Visio.Online",iu:"feba3d98f7c0481c8b63754573a80618-7311e9e0-365d-4a1b-b0fb-a238e0bc7528-6955"},{namespace:"Office.DNM.Sandbox",iu:"b0aae8a3009047b9bf4d3b17439319b6-e96e56cc-5657-463a-a2f2-dc8c0fb9d41b-7136"}]},114:function(u,D,F){function I(O,T){Object(H.b)(O,1,function(){return"WebSink:"+T})}F.d(D,"a",function(){return Q});var H=F(100),L=F(101),E=F(116),aa=
F(115),Q=function(){function O(T){this.Tbd=[];this.stats=Object(aa.b)();this.aZe=1E3;this.R7e=500;this.Rqd=100;this.eu=[];this.enabled=!0;T&&T.eGk&&(this.R7e=T.eGk)}O.prototype.init=function(T,K){if(!T.endpointUrl||!K.uuid||!K.Yhg)return this.enabled=!1,I(0,2),!1;T.uploadFrequency&&(this.aZe=T.uploadFrequency);T.batchSize&&(this.Rqd=T.batchSize);this.OBd=T;this.$Af=K;return!0};O.prototype.isInitialized=function(){if(this.enabled){if(this.OBd)return!0;I(1,1)}return!1};O.prototype.Rek=function(T){var K=
this;Object.keys(T).forEach(function(X){Object(aa.c)(K.stats[X])?Object(aa.c)(T[X])?K.stats[X]+=T[X]:K.stats[X]=T[X]:X==="wr".toString()&&Object.keys(T.wr).forEach(function(P){K.stats.wr[P]=K.stats.wr[P]+T.wr||T.wr[P]})})};O.prototype.ljl=function(){var T=this;if(this.isInitialized()){this.stats.s=1;try{this.rTb=this.$Af.Yhg(),this.rTb.addEventListener("message",function(K){K=K.data;switch(K.t){case 1:T.Hoj();break;case 4:T.Rek(K.d);break;case 5:I(1,K.d);break;default:I(1,14)}}),this.rTb.addEventListener("error",
function(){I(1,12);1===T.stats.s&&T.f4f()}),this.rTb.addEventListener("errormessage",function(){I(1,13)})}catch(K){I(1,10),this.f4f()}}};O.prototype.Hoj=function(){this.isInitialized()&&(this.stats.s=2,Object(H.b)(2,1,function(){return"WebSink:Loaded"}),this.rTb.postMessage({t:2,d:this.OBd}),this.jLc())};O.prototype.f4f=function(){this.stats.s=4;this.shutdown(!1)};O.prototype.jLc=function(){var T=Object(aa.a)(),K=this.stats,X=this.eu.slice(0,this.Rqd),P=X.length;this.eu=this.eu.slice(this.Rqd);try{P&&
(K.pw+=P,this.rTb.postMessage({t:3,d:X}))}catch(ea){I(1,11)}finally{T=Object(aa.a)()-T,K.md+=T,T>=K.mm&&(K.mm=T,K.mn=P),this.zxc&&clearTimeout(this.zxc),this.zxc=setTimeout(this.jLc.bind(this),this.aZe)}};O.prototype.GBe=function(T,K){for(var X=0;X<this.Tbd.length;X++){var P=this.Tbd[X],ea=P.name,ia=!1;if(3!==K||"EventThrottler"===ea){var ja=Object(aa.a)();try{ia=P.LX(T)}catch(C){}P=Object(aa.a)()-ja;this.stats.pd[ea]=this.stats.pd[ea]+P||P;if(!ia)return this.stats.po[ea]=this.stats.po[ea]+1||1,!1}}T.dataFields.push(Object(L.d)("OTelJS.Sink",
"WebSink"));return!0};O.prototype.aEe=function(T){2===this.stats.s||this.eu.length<this.R7e?(this.stats.q+=1,this.eu.push(T)):(I(1,3),this.stats.s=3,this.shutdown(!1))};O.prototype.sendTelemetryEvent=function(T){this.enabled&&this.GBe(T,1)&&this.aEe({event:T,t:1})};O.prototype.Elh=function(T){this.enabled&&this.GBe(T,2)&&this.aEe({event:T,t:2})};O.prototype.Llh=function(T,K){this.enabled&&this.GBe(T,K)&&this.aEe({event:T,t:K})};O.prototype.shutdown=function(T){if(this.isInitialized())try{this.stats.pm=
this.eu.length,E.a(this.OBd,{uuid:this.$Af.uuid,Ozl:T,stats:this.stats},this.eu),this.eu=[]}catch(K){I(1,30)}this.enabled=!1;this.zxc&&clearTimeout(this.zxc)};return O}()},115:function(u,D,F){function I(){var E;return E={},E.md=0,E.mm=0,E.mn=0,E.q=0,E.po={},E.pw=0,E.wa=0,E.wp=0,E.wd=0,E.wr={},E.ws=0,E.pm=0,E.sp=0,E.ss=0,E.sd=0,E.pd={},E.d=0,E.b=0,E.s=0,E}function H(){return Date.now()}function L(E){return"number"===typeof E}F.d(D,"c",function(){return L});F.d(D,"a",function(){return H});F.d(D,"b",
function(){return I});"object"===typeof window&&"object"===typeof window.performance&&"function"===typeof window.performance.now&&(H=function(){return window.performance.now()})},116:function(u,D,F){function I(bb,Ya,ua){function Ma(Mb,Hb,vb,Xb){var Uc,hb=Hb,Zb=0;if("undefined"!==typeof hb&&""!==hb){Object(K.c)(Hb)&&(Zb=6);switch(vb){case 3:Zb=6;break;case 2:Zb=4;break;case 4:Zb=8;break;case ia:Zb=9;break;case 0:hb="string"===typeof hb?hb.substr(0,25E3):hb}if(Db){Hb=Xb.data;Xb=Xb.ext.metadata;for(vb=
0;vb<Mb.length-1;){var Fc=Mb[vb];if(!Fc)return;if(Hb[Fc]){if("object"!==typeof Hb)return}else Hb[Fc]={};Hb=Hb[Fc];if(Zb){var ob=Xb.f||{};ob[Fc]||(ob[Fc]={});Xb.f=ob;Xb=ob[Fc]}vb++}Mb=Mb[vb];"object"===typeof Hb&&"object"!==typeof Hb[Mb]&&(Hb[Mb]=hb,Zb&&(Xb.f=Object(Q.a)(Object(Q.a)({},Xb.f),(Uc={},Uc[Mb]={t:Zb},Uc))))}else Uc=Mb.join(ma),Xb.data[Uc]=Hb,Zb&&(Xb.ext.metadata.f[Uc]={t:Zb})}}function Ca(Mb,Hb,vb){Mb&&Mb.forEach(function(Xb){var Uc=Xb.classification;if(4===Uc||1===Uc)Uc=Xb.name.split(ma),
Uc[0]!==C&&(Hb&&Uc.unshift(ja),Ma(Uc,Xb.value,Xb.dataType,vb))})}var Va,Za,Db=!0===(null===(Za=null===(Va=bb.extensionConfig)||void 0===Va?void 0:Va.PostChannel)||void 0===Za?void 0:Za.enableCompoundKey),Lb=[],yb={},Bc=Ya.uuid();Va=bb.minSinkLimit;Va=Object(K.c)(Va)?Va:X;ua=ua.slice(0,Va);var tb=Ya.stats.pw+1;ua.forEach(function(Mb){var Hb=Mb.event.telemetryProperties.ariaTenantToken;a:{var vb=tb;if(1===Mb.t){Mb=Mb.event;var Xb=Mb.timestamp,Uc=(Xb?new Date(Xb):new Date).toISOString();Xb=Mb.eventFlags.diagnosticLevel;
if(bb.enableOptionalEvents||10===Xb||110===Xb||120===Xb){var hb=Mb.eventName;Xb={name:hb,time:Uc,ver:"4.0",iKey:"o:"+Hb.substr(0,32),ext:{sdk:{seq:vb},metadata:{f:{}}},data:{}};Ma([pa,Da],Ea,0,Xb);Ma(["baseData","properties","version"],ta+"="+T.a,0,Xb);Ca(bb.persistentDataFields,!1,Xb);Ma([pa,Z],hb,0,Xb);Ma([pa,qa],vb,2,Xb);Ma([pa,ya],Uc,ia,Xb);Ma([pa,Ka],Bc+ma+vb,0,Xb);vb="custom";if(Uc=Mb.eventContract)hb=Uc.name,Ma([pa,la],hb,0,Xb),vb+=ma+hb.toLowerCase().replace(/\./g,"_"),Ca(Uc.dataFields,!1,
Xb);Xb.data.baseType=vb;Ca(Mb.dataFields,!0,Xb);Mb=Xb;break a}}Mb=void 0}Mb&&(Lb.push(Mb),yb[Hb]=!0,tb+=1)});return[Lb,Object.keys(yb)]}function H(bb,Ya,ua){for(var Ma="",Ca="",Va=0;Va<bb.length;Va++){Ca=Ma+Ca+JSON.stringify(bb[Va]);if(Ca.length>Ya)break;Ma=Ca;ua.sp+=1;Ca=sa}return Ma}function L(bb,Ya,ua){Ya=H(Ya,ea,ua);var Ma=new XMLHttpRequest;Ma.onload=function(){var Ca=Ma.responseText;Ca&&(Ca=JSON.parse(Ca),Ca.S_h&&(ua.ss+=parseInt(Ca.S_h,10)),Ca.VOk&&(ua.sd+=parseInt(Ca.VOk,10)))};Ma.onerror=
function(){ua.sd=ua.sp};Ma.open(oa,bb);Ma.send(Ya)}function E(bb,Ya,ua){var Ma=Ya.length;if(null===navigator||void 0===navigator?0:navigator.sendBeacon){var Ca=H(Ya,P,ua);if(navigator.sendBeacon(bb,Ca))ua.ss=ua.sp;else{for(Ca=0;Ca<Ma;){var Va=JSON.stringify(Ya[Ca]);if(!navigator.sendBeacon(bb,Va))break;Ca++}ua.ss=Ca;ua.sd=ua.sp-Ca}}else ua.sd=Ma}function aa(bb,Ya,ua){if(Ha)Object(O.b)(0,1,function(){return Ga+20});else try{var Ma=I(bb,Ya,ua),Ca=Ma[0],Va=Ma[1];if(0!==Ca.length&&0!==Va.length){var Za=
bb.endpointUrl+"?cors=true&content-type=application/x-json-stream&apikey="+Va.join(),Db=Ya.stats;Ya.Ozl?E(Za,Ca,Db):L(Za,Ca,Db);Ha=!0}}catch(Lb){Object(O.b)(0,1,function(){return Ga+22})}}F.d(D,"a",function(){return aa});var Q=F(104),O=F(100),T=F(117),K=F(115),X=500,P=65536,ea=4194304,ia="dt",ja="Data",C="zC",pa="Event",Z="Name",qa="Sequence",ya="Time",Ka="Id",Da="Source",la="Contract",ma=".",Ea="OTelJS",ta=Ea+"Min",Ga=ta+":",oa="POST",sa="\n",Ha=!1},117:function(u,D,F){F.d(D,"a",function(){return I});
var I="4.13.6"},78:function(u,D,F){F.r(D);var I=F(92);F.d(D,"TelemetryFactoryGlobal",function(){return I.a});var H=F(95);F.d(D,"logUserAction",function(){return H.f});F.d(D,"logActivity",function(){return H.d});F.d(D,"ScorecardAggregateMethod",function(){return H.a});F.d(D,"logActivityForExperiment",function(){return H.e});F.d(D,"sendTelemetryEvent",function(){return H.o});F.d(D,"sendActivityEvent",function(){return H.i});F.d(D,"sendDirectNumericEvent",function(){return H.j});F.d(D,"sendOtelEvent",
function(){return H.n});F.d(D,"sendOtelCustomerContent",function(){return H.l});F.d(D,"sendOtelDirectNumeric",function(){return H.m});F.d(D,"sendUserActionEvent",function(){return H.p});F.d(D,"addNamespaceMapping",function(){return H.b});F.d(D,"setDNMToken",function(){return H.q});F.d(D,"flushAsync",function(){return H.c});F.d(D,"setEnabledState",function(){return H.r});F.d(D,"registerShutdownHook",function(){return H.h});F.d(D,"shutdown",function(){return H.s});F.d(D,"registerEventHandler",function(){return H.g});
F.d(D,"sendEventDirectlyToHandler",function(){return H.k});var L=F(96);F.d(D,"disableSessionLevelTelemetry",function(){return L.a});F.d(D,"setWorkerEnabledState",function(){return L.b});F.d(D,"startOtelWorker",function(){return L.c})},92:function(u,D,F){F.d(D,"a",function(){return I});var I=new (F(93).a)},93:function(u,D,F){F.d(D,"a",function(){return H});var I=F(94),H=function(){function L(){}L.prototype.createInstance=function(){return new I.a};return L}()},94:function(u,D,F){F.d(D,"a",function(){return E});
var I=F(95),H=F(96),L=F(102),E=function(){function aa(){}aa.prototype.sendTelemetryEvent=function(Q){Q&&Object(I.o)(Q)};aa.prototype.sendDirectNumericEvent=function(Q){Q&&Object(I.j)(Q)};aa.prototype.sendActivityEvent=function(Q){Q&&Object(I.i)(Q)};aa.prototype.sendUserActionEvent=function(Q){Q&&Object(I.p)(Q)};aa.prototype.addNamespaceMapping=function(Q,O){Q&&O&&Object(I.b)(Q,O)};aa.prototype.setDNMToken=function(Q,O){Q&&O&&Object(I.q)(Q,O)};aa.prototype.sendOtelEvent=function(Q){Q&&Object(I.n)(Q)};
aa.prototype.sendOtelCustomerContent=function(Q){Q&&Object(I.l)(Q)};aa.prototype.sendOtelDirectNumeric=function(Q){Q&&Object(I.m)(Q)};aa.prototype.setEnabledState=function(Q){Object(I.r)(Q)};aa.prototype.registerEventHandler=function(Q){Q&&Object(I.g)(Q)};aa.prototype.shutdown=function(){return Object(I.s)()};aa.prototype.setOtelWorkerEnabledState=function(Q,O){return Object(H.b)(Q,Object(L.b)(O))};aa.prototype.startOtelWorker=function(){return Object(H.c)()};return aa}()},95:function(u,D,F){function I(oa,
sa,Ha,bb,Ya,ua,Ma){X({name:null,actionName:oa,commandSurface:Ya,parentName:Ha,triggerMethod:bb,durationMs:ua,succeeded:sa,dataFields:Ma})}function H(oa,sa,Ha,bb){void 0===sa&&(sa=!0);void 0===Ha&&(Ha=0);void 0===bb&&(bb=[]);aa({name:oa,succeeded:sa,durationMs:Ha,dataFields:bb})}function L(oa,sa,Ha,bb,Ya,ua,Ma){void 0===Ha&&(Ha=Ga.Count);void 0===bb&&(bb=!0);void 0===Ya&&(Ya=0);void 0===ua&&(ua=[]);void 0===Ma&&(Ma=!1);if(null!==oa&&void 0!==oa&&""!==oa){var Ca=sa;if(null===sa||void 0===sa)if(Ha===
Ga.Count)Ca=1;else return;ua.push({name:"WAC_Experiment",string:Ha.toString()});ua.push({name:"WAC_Experiment_Value",double:Ca});ua.push({name:"WAC_Experiment_EventName",string:"WAC_Exp_"+oa+"_"+Ha.toString()});ua.push({name:"WAC_Experiment_AggregateOnlySucceeded",bool:Ma});aa({name:oa,succeeded:bb,durationMs:Ya,dataFields:ua})}}function E(oa){qa({kind:"event",event:oa,timestamp:(new Date).getTime()})}function aa(oa){qa({kind:"activity",event:oa,timestamp:(new Date).getTime()})}function Q(oa){qa({kind:"dnm",
event:oa,timestamp:(new Date).getTime()})}function O(oa){qa({kind:"otel",event:oa})}function T(oa){qa({kind:"otelcc",event:oa})}function K(oa){qa({kind:"oteldnm",event:oa})}function X(oa){qa({kind:"action",event:oa,timestamp:(new Date).getTime()})}function P(oa,sa){qa({kind:"addNamespaceMapping",namespace:oa,ariaTenantToken:sa})}function ea(oa,sa){qa({kind:"setDNMToken",namespace:oa,ariaTenantToken:sa})}function ia(){qa({kind:"flush"})}function ja(oa){(Ka=oa)||(Da=[])}function C(oa){Ea=oa}function pa(){Ea&&
Ea();qa({kind:"shutdown"});return Da.length+ma}function Z(oa){la=oa;Da.forEach(function(sa){return qa(sa)});Da=[]}function qa(oa){Ka&&(la?la(oa):Da.length<=ta?Da.push(oa):ma+=1)}function ya(oa){la&&la(oa)}F.d(D,"f",function(){return I});F.d(D,"d",function(){return H});F.d(D,"a",function(){return Ga});F.d(D,"e",function(){return L});F.d(D,"o",function(){return E});F.d(D,"i",function(){return aa});F.d(D,"j",function(){return Q});F.d(D,"n",function(){return O});F.d(D,"l",function(){return T});F.d(D,
"m",function(){return K});F.d(D,"p",function(){return X});F.d(D,"b",function(){return P});F.d(D,"q",function(){return ea});F.d(D,"c",function(){return ia});F.d(D,"r",function(){return ja});F.d(D,"h",function(){return C});F.d(D,"s",function(){return pa});F.d(D,"g",function(){return Z});F.d(D,"k",function(){return ya});var Ka=!1,Da=[],la,ma=0,Ea,ta=2E4,Ga;(function(oa){oa.Count="Count";oa.Avg="Avg";oa.Sum="Sum"})(Ga||(Ga={}))},96:function(u,D,F){function I(){la=!1}function H(){if(!Ka||!ya)return{succeeded:!1,
failureReason:"NotEnabled"};Object(pa.h)(function(){});var Ga=ya();if(!Ga)return{succeeded:!1,failureReason:"NoSettings"};if(!Ga.ulsLoggingMethods||!Ga.ulsLoggingMethods.sendTraceTag)return{succeeded:!1,failureReason:"ULSLoggingMethods"};var oa=Ga.ulsLoggingMethods.sendTraceTag;if(qa)return Object(Z.c)("WebSinkAlreadyInitialized",oa);var sa=Ga.workerUrl;if(!sa)return Object(Z.c)("WorkerUrl",oa);var Ha=Ga.telemetryLoggerSettings;if(!Ha)return Object(Z.c)("TelemetrySettings",oa);var bb=Ha.ariaEndpointUrl;
if(!Ha.ariaEndpointUrl)return Object(Z.c)("AriaUrl",oa);var Ya=Ha.alwaysOnMetadata;if(!Ya)return Object(Z.c)("AlwaysOnMetadata",oa);if(!Ga.uuid)return Object(Z.c)("Uuid",oa);Ga.batchSize&&(ma.lGh=Ga.batchSize);Object(X.c)().addListener(T);Ha.enableCustomerContent&&(Da=!0);Q(Ya,oa);Ya=Object(K.d)(Object(ja.a)(Ya));for(var ua=new P.a(void 0,void 0,{QIi:!0}),Ma=0,Ca=ia.a;Ma<Ca.length;Ma++){var Va=Ca[Ma];ua.Ooh(Va.namespace,Va.iu)}Ma=0;for(Ca=ia.b;Ma<Ca.length;Ma++)Va=Ca[Ma],ua.setDNMToken(Va.namespace,
Va.iu);var Za=new ea.a;Za.init({endpointUrl:bb,persistentDataFields:Ya,enableOptionalEvents:!0,extensionConfig:{PostChannel:{enableCompoundKey:!0}},enableCustomerContent:Object(C.b)(Ha.enableCustomerContent),minSinkLimit:Ga.minSinkLimit,batchSize:Object(C.b)(Ga.batchSize),uploadFrequency:Object(C.b)(Ga.batchFrequencyMs),custom:{enableDNM:Object(C.b)(Ha.enableDNM)}},{uuid:Ga.uuid,Yhg:function(){var Db=new Blob(["try{importScripts('".concat(encodeURI(sa),'\');}catch(e){self.postMessage("Error loading Worker script")}')],
{type:"application/javascript"});return new Worker(URL.createObjectURL(Db))}});Ha.samplingIsEnabled&&(Object(Z.b)(Za,Ha)||oa(541411083,226,15,"Could not enable sampler"));ua.G3h(Za);qa={Ocg:function(){return ua},t4d:function(){return Za},getSettings:function(){return Ga},sendTraceTag:oa};Object(pa.g)(function(Db){L(Db)});return{succeeded:!0}}function L(Ga){if(qa){qa.sendTraceTag(541411082,226,50,"SendToWorkerApi with "+Ga.kind);var oa=Object(C.a)(),sa=void 0,Ha=qa.Ocg(),bb=Ha.sendTelemetryEvent.bind(Ha);
switch(Ga.kind){case "addNamespaceMapping":Ha.Ooh(Ga.namespace,Ga.ariaTenantToken);return;case "setDNMToken":Ha.setDNMToken(Ga.namespace,Ga.ariaTenantToken);return;case "flush":return;case "shutdown":bb=qa.t4d().stats;la&&Object(Z.d)(bb,ma,qa.Ocg());qa.t4d().shutdown(!0);la&&Object(Z.e)(bb,ma,qa.sendTraceTag);return;case "event":sa=O(Object(K.c)(Ga.event),Ga);break;case "dnm":sa=O(Object(K.b)(Ga.event),Ga);bb=Ha.sendDirectNumericEvent.bind(Ha);break;case "action":sa=Ga.event;null==sa.name&&(sa.name=
Ea,null!=sa.actionName&&(sa.name+=sa.actionName));sa=Object(K.e)(sa);sa=O(sa,Ga);break;case "activity":sa=Ga.event;null==sa||null==sa.name||0<=sa.name.indexOf("Office.")||(sa.name=ta+sa.name);sa=Object(K.a)(sa);sa=O(sa,Ga);break;case "otel":sa=Ga.event.otelEvent;break;case "otelcc":Da&&(sa=Ga.event.otelEvent,bb=Ha.Elh.bind(Ha));break;case "oteldnm":sa=Ga.event.otelEvent;bb=Ha.sendDirectNumericEvent.bind(Ha);break;default:Ga}sa&&(Ga=Object(C.a)()-oa,oa=Object(C.a)(),bb(sa),bb=Object(C.a)()-oa,ma.conversionDurationMs+=
Ga,ma.logDurationMs+=bb,ma.processed+=1)}}function E(Ga,oa){Ga&&oa?(Ka=!0,ya=oa,Object(pa.h)(function(){return H()})):(Ka=!1,ya=void 0)}function aa(){var Ga=H();if(!Ga.succeeded)return Ga;var oa=qa.t4d();oa.ljl();var sa=qa.getSettings().telemetryLoggerSettings;Object(Z.a)(oa,sa);return Ga}function Q(Ga,oa){Ga.name?(Ea="Office.".concat(Ga.name,".Online.UserAction."),ta="Office.".concat(Ga.name,".Online.Data.Activity.")):oa(541411084,226,100,"Cannot determine the App for UserActionEvent, using generic UserAction event name.")}
function O(Ga,oa){Ga.timestamp=oa.timestamp;return Ga}function T(Ga){if(qa){var oa=Ga.message(),sa=50,Ha=Ga.level;0===Ha?sa=10:1===Ha&&(sa=15);1===Ga.category&&"WebSink"===oa.substring(0,7)&&qa.sendTraceTag(540657436,226,sa,oa)}}F.d(D,"a",function(){return I});F.d(D,"b",function(){return E});F.d(D,"c",function(){return aa});var K=F(105),X=F(100),P=F(109),ea=F(114),ia=F(113),ja=F(108),C=F(102),pa=F(95),Z=F(97);(function(){throw Error();});var qa,ya,Ka=!1,Da=!1,la=!0,ma={processed:0,conversionDurationMs:0,
logDurationMs:0,lGh:0},Ea="Office.Online.UserAction",ta="Office.Online.Data.Activity"},97:function(u,D,F){function I(P,ea){if(ea.wacAriaThrottlingIsEnabled){var ia=new T.a("WebSink",P);ia.t7k(Object(X.b)(ea.wacAriaSingleEventThrottlePerSec));ia.p8k(Object(X.b)(ea.wacAriaTotalEventsThrottlePerSec));(ea=ea.otelEventNamesToBeSuppressedCommaSeparated)&&ea.split(",").forEach(function(ja){ia.C5k(ja)});P.Tbd.push(ia)}}function H(P,ea){var ia=ea.alwaysOnMetadata;if(!ia)return!1;var ja=ia.loggableUserId;ia=
ia.sessionId;ea=ea.sampleRate;if("number"===typeof ea){var C=new K.a;C.U6k(ea);if(ja&&C.N0f("PrimaryIdentityHash",ja)||ia&&C.N0f("SessionId",ia))return P.Tbd.push(C),!0}return!1}function L(P,ea,ia){P=JSON.stringify(Object(Q.a)(Object(Q.a)({},ea),P));ia(526513554,226,50,P)}function E(P,ea,ia){ea={eventName:"Office.Online.Telemetry.OTelJS.WebSink.Session.Stats",dataFields:[Object(O.c)("Queued",P.q),Object(O.c)("PassedToWebWorker",P.pw),Object(O.c)("WebWorkerAccepted",P.wa),Object(O.c)("WebWorkerProcessed",
P.wp),Object(O.c)("WebWorkerDropped",P.wd),Object(O.c)("WebWorkerSent",P.ws),Object(O.b)("MessagingDurationMs",P.md),Object(O.b)("MaxMessagingDurationMs",P.mm),Object(O.c)("MaxMessagingDurationNumEvents",P.mn),Object(O.c)("WebSinkBatchSize",ea.lGh),Object(O.b)("WebWorkerProcessingDurationMs",P.d),Object(O.b)("ConversionDurationMs",ea.conversionDurationMs),Object(O.b)("LogDurationMs",ea.logDurationMs),Object(O.c)("Bytes",P.b),Object(O.c)("WebWorkerStatus",P.s)],eventFlags:{samplingPolicy:191,diagnosticLevel:110}};
if(P.po)for(var ja in P.po)"EventThrottler"!==ja&&"Sampler"!==ja&&"DiagnosticLevel"!==ja||ea.dataFields.push(Object(O.c)("PreprocessedOut."+ja,P.po[ja]));ia.sendTelemetryEvent(ea)}function aa(P,ea){ea(526513555,226,15,"Failed to initialize worker because "+P);return{succeeded:!1,failureReason:P}}F.d(D,"a",function(){return I});F.d(D,"b",function(){return H});F.d(D,"e",function(){return L});F.d(D,"d",function(){return E});F.d(D,"c",function(){return aa});var Q=F(104),O=F(101),T=F(98),K=F(103),X=F(102)},
98:function(u,D,F){F.d(D,"a",function(){return E});var I=F(101),H=F(100),L=F(99),E=function(){function aa(Q,O){this.LXh=Q;this.Vyf=O;this.name="EventThrottler";this.OFd=0;this.mSb={};this.Y3e={};this.tef=Date.now();this.dzd={}}aa.prototype.t7k=function(Q){this.dgf=Q};aa.prototype.p8k=function(Q){this.hgf=Q};aa.prototype.C5k=function(Q){this.dzd[Q]=0};aa.prototype.LX=function(Q){Q=Q.eventName;if("Office.Telemetry.OTelJS.EventThrottled"===Q)return!0;var O=!0;1E3<Date.now()-this.tef&&(this.tef=Date.now(),
this.OFd=0,this.mSb={});this.mSb[Q]=this.mSb[Q]+1||1;Q in this.dzd?O=this.BKd(this.mSb[Q],this.dzd[Q],"MaxNamedEventsPerSecond",Q):"number"===typeof this.dgf&&(O=this.BKd(this.mSb[Q],this.dgf,"MaxSingleEventsPerSecond",Q));"number"===typeof this.hgf&&(this.OFd++,O&&(O=this.BKd(this.OFd,this.hgf,"MaxTotalEventsPerSecond",Q)));return O};aa.prototype.BKd=function(Q,O,T,K){return Q>O?(Q===O+1&&this.Vyf&&!this.Y3e[K]&&(this.Y3e[K]=!0,this.Vyf.sendTelemetryEvent({eventName:"Office.Telemetry.OTelJS.EventThrottled",
telemetryProperties:{ariaTenantToken:L.a,nexusTenantToken:1723},eventFlags:{diagnosticLevel:110},dataFields:[Object(I.d)("SinkName",this.LXh||""),Object(I.d)("ThrottledEvent.Name",K),Object(I.c)(T,O)]})),Object(H.b)(2,1,function(){return"1DS Sink Event Throttle: Exceeded ".concat(O," ").concat(T,": ").concat(K)}),!1):!0};return aa}()},99:function(u,D,F){F.d(D,"a",function(){return I});F(100);var I="f998cc5ba4d448d6a1e8e913ff18be94-dd122e0a-fcf8-4dc5-9dbb-6afac5325183-7405"}});V=window.dynamicScriptLoaderDependencies=
[{identifier:"appChrome",dependencies:["common"]},{identifier:"sharedComments",dependencies:["common","common50","comment-pane-strings"]},{identifier:"floatingContainerManager",dependencies:["common","common50"]},{identifier:"versionHistory",dependencies:["common","common50","office-version-history-strings","friendly-dates-strings","version-history-sprite"]},{identifier:"colorPickerManager",dependencies:["common","common50"]},{identifier:"selectionPaneManager",dependencies:["common","common50"]},
{identifier:"headerFooterManager",dependencies:["common","common50"]},{identifier:"taskPanes",dependencies:["common","common50"]},{identifier:"liveActor",dependencies:["common","common50","powerpoint-live-strings","office-common-strings"]},{identifier:"immersiveReader",dependencies:["common"]},{identifier:"slideshowToolbar",dependencies:["common","common50","powerpoint-slideshow-toolbar-strings"]},{identifier:"inkButton",dependencies:["common","common50","powerpoint-slideshow-toolbar-strings"]},{identifier:"rehearsalSummaryPage",
dependencies:["common","common50","powerpoint-presenter-coach-strings"]},{identifier:"voiceUI",dependencies:["common","common50"]},{identifier:"catchUpActivity",dependencies:["common","common50","powerpoint-catchup-activity-intl"]},{identifier:"agendaConverter",dependencies:["common","common50","office-common-strings","powerpoint-agenda-to-ppt-strings"]},{identifier:"audioPlayback",dependencies:["common"]},{identifier:"powerpoint-ribbon-intl",isLocalized:!0},{identifier:"ppt-ribbon-sprite-lazy",isLocalized:!0},
{identifier:"powerpoint-editor-intl",isLocalized:!0},{identifier:"ppt-editor-sprite",isLocalized:!0},{identifier:"ppt-ribbon-sprite-ext",isLocalized:!0},{identifier:"comment-pane-strings",isLocalized:!0},{identifier:"office-version-history-strings",isLocalized:!0},{identifier:"friendly-dates-strings",isLocalized:!0},{identifier:"version-history-sprite",isLocalized:!0},{identifier:"tellme-strings",isLocalized:!0},{identifier:"powerpoint-live-strings",isLocalized:!0},{identifier:"powerpoint-presenter-coach-strings",
isLocalized:!0},{identifier:"powerpoint-agenda-to-ppt-strings",isLocalized:!0},{identifier:"office-common-strings",isLocalized:!0},{identifier:"powerpoint-slideshow-toolbar-strings",isLocalized:!0},{identifier:"accessibility-checker-pane-strings",isLocalized:!0},{identifier:"audio-settings-strings",isLocalized:!0},{identifier:"powerpoint-discoverability-strings",isLocalized:!0},{identifier:"powerpoint-ribbon-mlr-intl",isLocalized:!0},{identifier:"ppt-ribbon-mlr-sprite-lazy",isLocalized:!0},{identifier:"ppt-ribbon-mlr-sprite",
isLocalized:!0},{identifier:"ppt-ribbon-sprite",isLocalized:!0},{identifier:"powerpoint-ribbon-intl-lazy",isLocalized:!0},{identifier:"powerpoint-ribbon-mlr-intl-lazy",isLocalized:!0},{identifier:"powerpoint-catchup-activity-intl",isLocalized:!0}];var y=function(u){function D(I){if(F[I])return F[I].exports;var H=F[I]={i:I,l:!1,exports:{}};u[I].call(H.exports,H,H.exports,D);H.l=!0;return H.exports}var F={};D.m=u;D.c=F;D.d=function(I,H,L){D.o(I,H)||Object.defineProperty(I,H,{enumerable:!0,get:L})};
D.r=function(I){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(I,Symbol.toStringTag,{value:"Module"});Object.defineProperty(I,"__esModule",{value:!0})};D.t=function(I,H){H&1&&(I=D(I));if(H&8||H&4&&"object"===typeof I&&I&&I.caa)return I;var L=Object.create(null);D.r(L);Object.defineProperty(L,"default",{enumerable:!0,value:I});if(H&2&&"string"!=typeof I)for(var E in I)D.d(L,E,function(aa){return I[aa]}.bind(null,E));return L};D.n=function(I){var H=I&&I.caa?function(){return I["default"]}:
function(){return I};D.d(H,"a",H);return H};D.o=function(I,H){return Object.prototype.hasOwnProperty.call(I,H)};D.p="";return D(D.s="./lib/index.js")}({"../../.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js":function(u){function D(F,I){function H(O,T,K){if(0<=K.indexOf(O)){try{var X=", node was:"+JSON.stringify(O)}catch(ea){X=""}throw Error("Cyclic dependency"+X);}if(!~F.indexOf(O))throw Error("Found unknown node. Make sure to provided all involved nodes. Unknown node: "+
JSON.stringify(O));if(!aa[T]){aa[T]=!0;X=I.filter(function(ea){return ea[0]===O});if(T=X.length){K=K.concat(O);do{var P=X[--T][1];H(P,F.indexOf(P),K)}while(T)}E[--L]=O}}for(var L=F.length,E=Array(L),aa={},Q=L;Q--;)aa[Q]||H(F[Q],Q,[]);return E}u.exports=function(F){for(var I=[],H=0,L=F.length;H<L;H++){var E=F[H];0>I.indexOf(E[0])&&I.push(E[0]);0>I.indexOf(E[1])&&I.push(E[1])}return D(I,F)};u.exports.OUb=D},"./lib/DynamicScriptLoader.js":function(u,D,F){Object.defineProperty(D,"__esModule",{value:!0});
D.DynamicScriptLoader=void 0;var I=F("./lib/getOrderedScriptAndDependencies.js"),H=F("./lib/loadScript.js"),L=F("./lib/preloadScript.js");u=function(){function E(aa){var Q=this;this.config=aa;this.Ahh=new Map;this.ixb=new Map;this.Hfd=new Map;this.loadScript=function(O){var T=Q.config,K=T.crossOriginAttributeValue,X=T.loadScriptHandler,P=T.loadScriptWithRetryHandler,ea=(0,I.P1d)(O,Q.ixb);T=ea.map(function(ia){var ja=Q.Ahh.get(ia);ja||(ja=(P||X||H.loadScript)(ia,Q.k4d(ia),K,void 0,void 0,Q.jgg(ia)),
Q.Ahh.set(ia,ja));return ja});return Q.config.isRetryEnabled?Promise.all(T).then(function(){return O},function(){ea.forEach(function(ia,ja){var C=Q.Hfd.get(ia);C||(C=(0<ja?Q.Hfd.get(ea[ja-1]):Promise.resolve()).then(function(){return(P||X||H.loadScript)(ia,Q.k4d(ia),K,5,!0,Q.jgg(ia))}),Q.Hfd.set(ia,C))});return Q.Hfd.get(ea[ea.length-1]).then(function(){return O})}):Promise.all(T).then(function(){return O})};this.preloadScript=function(O){(0,I.P1d)(O,Q.ixb).forEach(function(T){return(0,L.preloadScript)(Q.k4d(T),
Q.config.crossOriginAttributeValue)})};aa.knownScripts&&aa.knownScripts.forEach(function(O){var T=O.identifier.toLowerCase();if(Q.ixb.has(T))throw Error("The knownScripts passed into the DynamicScriptLoader config contains multiple entries for the script with identifier: ".concat(T));Q.ixb.set(T,O)})}E.prototype.getConfig=function(){return this.config};E.prototype.jgg=function(aa){aa=this.ixb.get(aa)||{identifier:aa};return this.config.resolveSriHash?this.config.resolveSriHash(aa):""};E.prototype.k4d=
function(aa){aa=this.ixb.get(aa)||{identifier:aa};return this.config.resolveScript(aa)};return E}();D.DynamicScriptLoader=u},"./lib/appResourceLoader.js":function(u,D,F){Object.defineProperty(D,"__esModule",{value:!0});D.CAi=D.BWj=D.init=void 0;var I=F("./lib/loadScript.js"),H=!1,L,E;D.init=function(Q,O,T){L=Q;E=T;F.p=O;H=!0};D.BWj=function(Q,O){O=L(Q,O);return(0,I.loadScript)(Q,O,"anonymous",5)};var aa=new Map;D.CAi=function(Q,O){return function X(K){if(!H)throw Error("appResourceLoader not initialized");
if(aa.has(K))return aa.get(K);var P=Date.now(),ea=-1,ia=[];if(Q[K]&&Q[K].dependencies)for(var ja=0,C=Q[K].dependencies;ja<C.length;ja++)ia.push(X(C[ja]));ja=0===ia.length?O(K):Promise.all(ia).then(function(){ea=Date.now()-P;return O(K)});ja=ja.then(function(pa){if(E){var Z="Chunk ".concat(K," loaded in ").concat(Date.now()-P," ms");-1!==ea&&(Z+=" (".concat(ea," ms for extra ").concat(ia.length," deps)"));E(0,306,50,Z)}return pa}).catch(function(pa){E&&E(0,306,10,pa)});aa.set(K,ja);return ja}}},"./lib/getOrderedScriptAndDependencies.js":function(u,
D,F){Object.defineProperty(D,"__esModule",{value:!0});D.P1d=void 0;var I=F("../../.store/toposort@1.0.7-e70287510c5359da9183/node_modules/toposort/index.js");D.P1d=function(H,L){function E(){var K=Q.shift();aa.add(K);var X=L.get(K);X&&X.dependencies&&X.dependencies.forEach(function(P){P=P.toLowerCase();aa.has(P)||Q.push(P);O.push([P,K])})}for(var aa=new Set,Q=[H.toLowerCase()],O=[];0<Q.length;)E();var T=[];aa.forEach(function(K){return T.push(K)});return I.OUb(T,O)}},"./lib/index.js":function(u,D,
F){var I=this&&this.GEl||(Object.create?function(H,L,E,aa){void 0===aa&&(aa=E);var Q=Object.getOwnPropertyDescriptor(L,E);if(!Q||("get"in Q?!L.caa:Q.writable||Q.configurable))Q={enumerable:!0,get:function(){return L[E]}};Object.defineProperty(H,aa,Q)}:function(H,L,E,aa){void 0===aa&&(aa=E);H[aa]=L[E]});u=this&&this.__exportStar||function(H,L){for(var E in H)"default"===E||Object.prototype.hasOwnProperty.call(L,E)||I(L,H,E)};Object.defineProperty(D,"__esModule",{value:!0});u(F("./lib/DynamicScriptLoader.js"),
D);u(F("./lib/loadScript.js"),D);u(F("./lib/preloadScript.js"),D);u(F("./lib/appResourceLoader.js"),D)},"./lib/loadScript.js":function(u,D){function F(I,H,L,E,aa,Q,O){return new Promise(function(T,K){var X=document.createElement("script");X.async=!1;X.src=H;void 0!==L&&(X.crossOrigin=L);aa&&""!==aa&&(X.setAttribute("integrity","sha256-".concat(aa)),L||(X.crossOrigin="anonymous"));X.onload=function(){Q?Q(I):T(I)};X.onerror=function(){if(E&&0<E)document.head.removeChild(X),F(I,H,L,E-1,aa,Q||T,O||K);
else{var P=Error("Failed to download the script with identifier: ".concat(I," at url: ").concat(H));O?O(P):K(P)}};document.head.appendChild(X)})}Object.defineProperty(D,"__esModule",{value:!0});D.loadScript=void 0;D.loadScript=function(I,H,L,E,aa,Q){return F(I,H+(aa?"?cache-bust=true":""),L,E,Q)}},"./lib/preloadScript.js":function(u,D){Object.defineProperty(D,"__esModule",{value:!0});D.preloadScript=void 0;D.preloadScript=function(F,I){var H=document.createElement("link");H.rel="preload";H.href=F;
H.setAttribute("as","script");void 0!==I&&(H.crossOrigin=I);document.head.appendChild(H)}}});Type.registerNamespace("Sys");window.IEnumerator=0;window.IEnumerable=1;(()=>{Type.registerNamespace("$$sc");window.$$ct=e;window.$$as=function(u,D){return u.isInstanceOfType(D)?D:null};m.Task.wLa=new A;v.a._default=new w;v.a.ry=v.a._default})();Type.registerNamespace("Otel");window.otel=J;V;window.getDynamicScriptLoaderResolver=function(u,D,F,I,H,L,E,aa){return function(Q,O){var T=H?"":".min",K=D,X=I,P=!1;
L&&(P=u.some(function(ea){return ea.identifier==Q||null!=ea.dependencies&&-1<ea.dependencies.indexOf(Q)}))&&(K=L+(O?"":"webpack/"),X="localization/"+aa,T=E);return F&&!P&&(P=Q.toLowerCase()+T+".js",F[P])?F[P]:K+(O?X+"\\":"")+Q+T+".js"}};window.newDynamicScriptLoader=function(u,D,F,I,H,L,E,aa,Q){var O=getDynamicScriptLoaderResolver(D,F,I,H,L,E,aa,Q),T={resolveScript:function(K){return O(K.identifier,K.isLocalized)},crossOriginAttributeValue:u,knownScripts:D,loadScriptHandler:null};u=new y.DynamicScriptLoader(T);
u.BXe=function(K){T.loadScriptHandler=K};return u};window.getDynamicScriptLoaderFunction=function(u){return u.loadScript};window.dynamicScriptLoader=y;window.loadPreCore=()=>{d.e(1).then(d.bind(null,1203))}},function(J,V,d){d.d(V,"a",function(){return h});const h=e=>{e.next||(e.next=function(){return this.moveNext()?{done:!1,value:this.get_current()}:{done:!0,value:void 0}},e[Symbol.iterator]=function(){return this});return e}},function(J,V,d){function h(e,m){return void 0==e||void 0==m?!1:"number"===
typeof e||"string"===typeof e?Object.getType(m).implementsInterface(e):e.isInstanceOfType(m)}d.d(V,"a",function(){return h})}]),RO;for(RO in jF)sA[RO]=jF[RO];

//# sourceMappingURL=https://res-dev.cdn.officeppe.net/1js/build/17844168/wdjs/ppteditDS.precore.js.map