'use strict';(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[14],{1214:function(J,V,d){d.r(V);J=d(0);var h=d(68),e=d(26),m=d(685),r=d(970),v=d(969),A=d(968),w=d(28);class y{constructor(ma,Ea,ta){this.VGg=this.Are=null;this.ua=ma;this.ia=Ea;this.rGa=ta}getId(){return"DesignerSuggestionApplicator"}applyTextToSmartArtSuggestion(ma,Ea,ta){Ea=Number.parseInvariant(Ea);ma=Object.assign(new r.a,{wCc:Object.assign(new m.a,{SuggestionSid:Ea,ShapeId:ta,CorrelationId:ma,ActiveSlideCid:this.ua.Ba.cid,
ActiveSlideSid:this.ua.Ba.sid})});this.ia.La(w.a.QNa,2,ma)}previewTextToSmartArtSuggestion(ma,Ea){ma=new A.a(ma,Ea);this.rGa.pbh(ma)}dismissTextToSmartArtPreview(ma){ma=new v.a(ma);this.rGa.obh(ma)}C3h(ma,Ea){this.Are=ma;this.VGg=Ea}showMoreSlideSuggestions(ma){this.Are&&(this.VGg(),this.ia.processAction(w.a.x6d,2),this.Are(ma))}}Object(J.a)(y,"DesignerSuggestionApplicator",null,[769,755]);class u{constructor(ma){this.ia=ma}getId(){return"ActionsExecutor"}execute(ma,Ea){for(const ta of Ea)16===(ta.data?
this.ia.La(ta.command,2,ta.data):this.ia.processAction(ta.command,2))&&e.a.J(38412323,802,50,"Executing actions with id '{0}' failed for command '{1}'",ma,ta.command)}}Object(J.a)(u,"ExecuteActions",null,[768,755]);var D=d(25),F=d(45),I=d(35);class H{constructor(ma,Ea){this.ia=ma;this.Q4c=Ea}getId(){return"FeedbackExecutor"}showFeedback(ma,Ea){if(D.AFrameworkApplication.sE)if(F.a.Va(Ea)||!this.Q4c.instance){const ta={};ta.Origin=ma;this.ia.La(I.a.giveFeedback,2,ta)}else this.Q4c.execute(ta=>{ta.yIb(Ea,
"PowerPointIdeasSurveyEnabled")})}}Object(J.a)(H,"ExecuteFeedback",null,[767,755]);var L=d(119),E=d(178),aa=d(169),Q=d(13),O=d(22);class T{constructor(ma,Ea,ta,Ga,oa,sa){this.Xta=null;this.isFeatureEnabled=!1;this.la=ta;this.ia=ma;this.Fa=Ea;this.TI=Ga;this.Zd=oa;this.uc=sa;this.qbe=!1}get re(){return this.Zd.instance}Ydb(ma,Ea){if(this.qbe&&(this.qbe=!1,(ma=Ea.instanceId)&&ma.length&&this.Zd.instance&&(Ea=this.Zd.instance.DZ(this.Xta.assetId),!Ea||!Ea.instanceId||Ea.instanceId===ma)))this.TI.hub.onIdeasPaneStateChanged(!1,
"unknown")}bM(ma,Ea,ta){if(!this.isFeatureEnabled)return 8;if(1===ta)return this.uc.Hj()?32:8;this.A5b()?this.qmg(ma):this.rxa(ma);return 32}Ns(ma,Ea,ta){if(!this.isFeatureEnabled)return 8;if(1===ta)return 32;this.qmg(ma);return 32}Tl(ma,Ea,ta){if(!this.isFeatureEnabled)return 8;if(1===ta)return 32;this.rxa(ma);return 32}mLe(ma,Ea,ta,Ga,oa){if(!this.isFeatureEnabled)return 8;if(1===ta)return 32;ma=this.M8f();if(!ma)return 8;ma.wha=oa;this.re.XCh(ma.instanceId);return 32}Z$g(){return 32}qmg(ma){this.A5b()&&
this.xsh(ma)}rxa(ma){this.qbe=!0;this.A5b()||this.xsh(ma);this.TI.hub.onIdeasPaneStateChanged(!0,w.a.Jz(ma))}xsh(ma){ma===w.a.ZNe?this.ia.La(w.a.ush,2,!0):this.ia.La(w.a.WNe,2,!0)}M8f(){if(this.re){const ma=this.re.c0b(this.Xta);return this.Zd.instance.DZ(ma)}return null}A5b(){const ma=this.M8f();return!!ma&&ma.taskpane.visibility}}Object(J.a)(T,"BasePaneActor",null,[]);var K=d(27),X=d(52),P=d(108),ea=d(38);class ia extends T{constructor(ma,Ea,ta,Ga,oa,sa,Ha){super(ma,Ea,ta,Ga,sa,Ha);this.Xta={};
this.Xta.assetId="FA000000017";this.Xta.sourceLocationOverrideResourceId=this.la.powerPointIdeasSourceLocationId;this.Zd.execute(bb=>{bb.GId(Object(Q.a)(this,this.Ydb,"onPaneClosed"))});this.isFeatureEnabled=this.la.powerPointIdeasIsEnabled;this.qv=oa}ub(){this.isFeatureEnabled&&(this.ia.pa(w.a.ZNe,X.a.application,Object(Q.a)(this,this.bM,"showHidePane"),4),this.ia.pa(w.a.zjd,X.a.application,Object(Q.a)(this,this.bM,"showHidePane"),4),this.ia.pa(w.a.Xdl,X.a.application,Object(Q.a)(this,this.bM,"showHidePane"),
4),this.ia.pa(w.a.Wdl,X.a.application,Object(Q.a)(this,this.bM,"showHidePane"),4),this.ia.pa(w.a.vsh,X.a.application,Object(Q.a)(this,this.bM,"showHidePane"),4),this.ia.pa(w.a.x6d,X.a.application,Object(Q.a)(this,this.Ns,"hidePane"),4),this.ia.pa(w.a.Dsh,X.a.application,Object(Q.a)(this,this.Tl,"showPane"),4),this.ia.pa(w.a.eOe,X.a.application,Object(Q.a)(this,this.Tl,"showPane"),4),this.ia.pa(w.a.mLe,X.a.application,Object(Q.a)(this,this.mLe,"setPaneTitle"),4),ea.a("Designer.QueryNewPane")||this.ia.pa(w.a.FDe,
X.a.application,Object(Q.a)(this,this.Z$g,"queryShowHidePane"),96),K.App.Hb.updateCommandUI())}xe(){this.Fa.Dc(L.AFrame.jj).bindAction(E.KeyInputManager.Na(aa.a.dqc,1),w.a.vsh)}Z$g(ma,Ea,ta,Ga,oa){return Object(O.a)(P.a,oa)&&this.la.powerPointIdeasIsEnabled&&this.TI.hub?32:8}Ydb(ma,Ea){super.Ydb(ma,Ea);this.qv.Skd(JSON.stringify({IdeasPaneOpen:!1}))}rxa(ma){super.rxa(ma);this.qv.Skd(JSON.stringify({IdeasPaneOpen:!0}))}}Object(J.a)(ia,"IdeasActor",T,[]);var ja=d(1064),C=d(530),pa=d(59),Z=d(32),qa=
d(528);class ya{constructor(ma){this.ia=ma}insertOnlinePicture(ma){ma=Object.assign(new C.a,{Action:"Insert",Caption:ma.caption,OriginalUrl:ma.sourceUrl,Height:ma.height,Width:ma.width,LicenseDisplayName:ma.licenseDisplayName,LicenseUrl:ma.licenseUrl,ThumbnailUrl:ma.thumbnailUrl,PageUrl:ma.pageUrl});this.ia.La(w.a.B8a,2,ma)}insertHtmlText(ma){const Ea=new ja.DictionaryPropertySet;Ea.setValue(pa.a.bU,ma.htmlText);Ea.setValue(pa.a.Had,!1);8===this.ia.La(Z.a.xad,2,Ea)&&(ma=Object.assign(new qa.a,{Wlc:!1,
oY:ma.htmlText}),this.ia.La(w.a.LHa,2,ma))}insertContentFromStreamUrl(){throw Error.notImplemented();}getId(){return"InsertContentExecutor"}}Object(J.a)(ya,"InsertContentExecutor",null,[754,755]);class Ka{}Object(J.a)(Ka,"ConfigurationProvider",null,[]);class Da{constructor(ma,Ea,ta,Ga,oa,sa){e.a.J(512262857,809,50,"PPTIdeasManager - Initialize");var Ha=JSON.parse(ma.Ga("611"));for(var bb in Ha){var Ya=Ha[bb];Ya.runtimeJs=D.AFrameworkApplication.Jj(Ha[bb].runtimeJs,5);F.a.Va(Ya.isEnabledBrs)||(Ya.isEnabled=
ma.ka(Ya.isEnabledBrs))}bb=ma.dca("613",0);Ya=JSON.parse(ma.Ga("612"));const ua=ma.Ga("664"),Ma=ma.Cc("700",0),Ca=ma.Ga("781");ma=ma.Ga("843");let Va=D.AFrameworkApplication.Jj("",5);"Relative"===ma?Va="":"Current"!==ma&&e.a.J(512262856,802,15,"Unknown value '{0}' for PowerPointIdeasScriptLocationOverride. Using 'Current' instead.",ma);Ha=Object.assign(new Ka,{channelId:"Ideas",registeredServices:Ha,rankingOrder:Ya,rankingPromotionRate:bb,approvedOriginPattern:ua,actionTrackingInterval:Ma,surveyName:Ca,
showFeedbackCard:D.AFrameworkApplication.sE,scriptLocation:Va});IdeasHub.ideasHubInstance=IdeasHub.setup(Ha,sa.Pub,e.a.J,[Ea,ta,Ga,oa],sa.Z4i());this.gPh=IdeasHub.ideasHubInstance}get hub(){return this.gPh}}Object(J.a)(Da,"PPTIdeasManager",null,[752,753]);class la{constructor(){this.Lle=this.K=null}get name(){return"PowerPointWebEditor.Ideas"}Wb(ma){this.K=ma;this.K.register(y,"PowerPointWebEditor.Ideas.DesignerSuggestionApplicator").as("PowerPointWebEditor.IApplyDesignerSuggestions").ma().na(()=>
new y(ma.resolve("PowerPointWebEditor.Graph.IGraphTopologyManager"),ma.resolve("Common.IActionManagerExtended"),ma.resolve("PowerPointWebEditor.ReplaceObject.IReplaceObjectEventNotifier")));this.K.register(H,"PowerPointWebEditor.Ideas.ExecuteFeedback").as("PowerPointWebEditor.Ideas.IExecuteFeedback").ma().na(()=>new H(ma.resolve("Common.IActionManagerExtended"),ma.Ka("Common.ISystemInitiatedFeedback")));this.K.register(ya,"PowerPointWebEditor.Ideas.InsertContentExecutor").as("PowerPointWebEditor.IInsertContentExecutor").ma().na(()=>
new ya(ma.resolve("Common.IActionManagerExtended")));this.K.register(u,"PowerPointWebEditor.Ideas.ExecuteActions").as("PowerPointWebEditor.Ideas.IExecuteActions").ma().na(()=>new u(ma.resolve("Common.IActionManagerExtended")));try{e.a.J(512262855,809,50,"PPTWebEditorIdeasPackage - Resolving IInfraredRuntimeManager");const Ea=ma.resolve("PowerPointWebEditor.Infrared.IInfraredRuntimeManager");e.a.J(512262854,809,50,"PPTWebEditorIdeasPackage - Resolved IInfraredRuntimeManager");this.K.register(Da,"PowerPointWebEditor.Ideas.PPTIdeasManager").as("PowerPointWebEditor.Ideas.IPPTIdeasManager").ma().na(()=>
new Da(ma.resolve("Common.IAppSettingsManager"),ma.resolve("PowerPointWebEditor.IApplyDesignerSuggestions"),ma.resolve("PowerPointWebEditor.Ideas.IExecuteFeedback"),ma.resolve("PowerPointWebEditor.IInsertContentExecutor"),ma.resolve("PowerPointWebEditor.Ideas.IExecuteActions"),Ea))}catch(Ea){throw e.a.J(512262853,809,10,"PPTWebEditorIdeasPackage - {0}",Ea),Ea;}}init(){const ma=this.K.resolve("Common.IAppSettingsManager");ma.ff(()=>{const Ea=ma.ka("610"),ta=this.K.resolve("PowerPointWebEditor.IApplicationSettings").dgb?
this.K.resolve("PowerPointWebEditor.IPPTRumTracker"):null;Ea?(this.K.resolve("PowerPointWebEditor.IInsertContentExecutor"),this.K.resolve("PowerPointWebEditor.IApplyDesignerSuggestions"),this.Lle=new ia(this.K.resolve("Common.IActionManagerExtended"),this.K.resolve("Common.IFocusManager"),this.K.resolve("PowerPointWebEditor.IApplicationSettings"),this.K.resolve("PowerPointWebEditor.Ideas.IPPTIdeasManager"),this.K.resolve("PowerPointWebEditor.IInboundHelper"),this.K.Ka("PowerPointWebEditor.IAppForOfficeManager"),
this.K.resolve("PowerPointWebEditor.IPresentationReader")),this.Lle.ub(),this.Lle.xe()):ta&&ta.Y9(ta.e5,ta.wTd)})}dispose(){}static main(){h.a.instance.Bc(new la)}}Object(J.a)(la,"PPTWebEditorIdeasPackage",null,[2,3]);Type.registerNamespace("PowerPointWebEditor.Ideas");la.main()}}]);

//# sourceMappingURL=https://res-dev.cdn.officeppe.net/1js/build/17844168/wdjs/ppteditDS.ideas.js.map